const verbsReview6 = [
  {entry: "adulor",
  infinitive: "adulārī",
  thirdPart: "adulātus sum",
  meanings: "flatter, fawn over"},
  {entry: "amplector",
    infinitive: "amplectī",
    thirdPart: "amplexus sum",
    meanings: "surround, embrace"},
  {entry: "arbitror",
    infinitive: "arbitrārī",
    thirdPart: "arbitrātus sum",
    meanings: "think, judge, observe"},
  {entry: "blandior",
    infinitive: "blandīrī",
    thirdPart: "blandītus sum",
    meanings: "flatter, compliment"},
  {entry: "confiteor",
    infinitive: "confitērī",
    thirdPart: "confessus sum",
    meanings: "confess"},
  {entry: "cōnor",
    infinitive: "cōnārī",
    thirdPart: "cōnātus sum",
    meanings: "try, attempt"},
  {entry: "ēgredior",
    infinitive: "ēgredī",
    thirdPart: "ēgressus sum",
    meanings: "exit, leave, step out"},
  {entry: "experior",
    infinitive: "experīrī",
    thirdPart: "expertus sum",
    meanings: "test, find out, experience"},
  {entry: "fābulor",
    infinitive: "fābulārī",
    thirdPart: "fābulātus sum",
    meanings: "chat, tell stories"},
  {entry: "fateor",
    infinitive: "fatērī",
    thirdPart: "fassus sum",
    meanings: "confess, admit"},
  {entry: "for",
    infinitive: "fārī",
    thirdPart: "fātus sum",
    meanings: "say, speak"},
  {entry: "fruor",
    infinitive: "fruī",
    thirdPart: "frūctus sum",
    meanings: "enjoy, engage in"},
  {entry: "fungor",
    infinitive: "fungī",
    thirdPart: "functus sum",
    meanings: "perform, administer"},
  {entry: "fūror",
    infinitive: "fūrārī",
    thirdPart: "fūratus sum",
    meanings: "steal, plunder"},
  {entry: "gradior",
    infinitive: "gradī",
    thirdPart: "grassus sum",
    meanings: "step, walk"},
  {entry: "hortor",
    infinitive: "hortārī",
    thirdPart: "hortātus sum",
    meanings: "urge, encourage"},
  {entry: "iocor",
    infinitive: "iocārī",
    thirdPart: "iocātus sum",
    meanings: "joke, jest, play"},
  {entry: "īrāscor",
    infinitive: "īrāscī",
    thirdPart: "īrātus sum",
    meanings: "rage, grow angry (at)"},
  {entry: "lābor",
    infinitive: "lābī",
    thirdPart: "lāpsus sum",
    meanings: "slip, slide, fall"},
  {entry: "largior",
    infinitive: "largīrī",
    thirdPart: "largītus sum",
    meanings: "grant, bestow"},
  {entry: "liceor",
    infinitive: "licērī",
    thirdPart: "licitus sum",
    meanings: "make an offer, appraise"},
  {entry: "liquor",
    infinitive: "liquī",
    thirdPart: "---",
    meanings: "flow, melt"},
  {entry: "loquor",
    infinitive: "loquī",
    thirdPart: "locūtus sum",
    meanings: "speak"},
  {entry: "mentior",
    infinitive: "mentīrī",
    thirdPart: "mentītus sum",
    meanings: "lie, tell lies, deceive"},
  {entry: "mercor",
    infinitive: "mercārī",
    thirdPart: "mercātus sum",
    meanings: "trade, deal"},
  {entry: "mereor",
    infinitive: "merērī",
    thirdPart: "meritus sum",
    meanings: "earn, deserve"},
  {entry: "mētior",
    infinitive: "mētīrī",
    thirdPart: "mētītus/mēnsus sum",
    meanings: "measure, distribute"},
  {entry: "minor",
    infinitive: "minārī",
    thirdPart: "minātus sum",
    meanings: "threaten"},
  {entry: "mīror",
    infinitive: "mīrārī",
    thirdPart: "mīrātus sum",
    meanings: "wonder, marvel"},
  {entry: "misereor",
    infinitive: "miserērī",
    thirdPart: "miseritus sum",
    meanings: "have pity, commiserate"},
  {entry: "mōrior",
    infinitive: "mōrī",
    thirdPart: "mortuus sum",
    meanings: "die"},
  {entry: "moror",
    infinitive: "morārī",
    thirdPart: "morātus sum",
    meanings: "delay, tarry, linger"},
  {entry: "nāscor",
    infinitive: "nāscī",
    thirdPart: "nātus sum",
    meanings: "be born"},
  {entry: "negōtior",
    infinitive: "negōtiārī",
    thirdPart: "negōtiātus sum",
    meanings: "do business, perform a task"},
  {entry: "oblīvīscor",
    infinitive: "oblīvīscī",
    thirdPart: "oblītus sum",
    meanings: "forget, neglect"},
  {entry: "orior",
    infinitive: "orīrī",
    thirdPart: "ortus sum",
    meanings: "rise, arise, originate"},
  {entry: "ōsculor",
    infinitive: "ōsculārī",
    thirdPart: "ōsculātus sum",
    meanings: "kiss"},
  {entry: "ōtior",
    infinitive: "ōtiārī",
    thirdPart: "ōtiātus sum",
    meanings: "be lazy, be at leisure, relax"},
  {entry: "partior",
    infinitive: "partīrī",
    thirdPart: "partītus sum",
    meanings: "share, divide, distribute"},
  {entry: "patior",
    infinitive: "patī",
    thirdPart: "passus sum",
    meanings: "endure, suffer, undergo, allow"},
  {entry: "polliceor",
    infinitive: "pollicērī",
    thirdPart: "pollicitus sum",
    meanings: "promise, pledge"},
  {entry: "potior",
    infinitive: "potīrī",
    thirdPart: "potītus sum",
    meanings: "obtain, take possession of"},
  {entry: "precor",
    infinitive: "precārī",
    thirdPart: "precātus sum",
    meanings: "pray, entreat"},
  {entry: "queror",
    infinitive: "querī",
    thirdPart: "questus sum",
    meanings: "complain, lament"},
  {entry: "reor",
    infinitive: "rērī",
    thirdPart: "rātus sum",
    meanings: "reckon, calculate"},
  {entry: "sequor",
    infinitive: "sequī",
    thirdPart: "secūtus sum",
    meanings: "follow, puruse"},
  {entry: "sortior",
    infinitive: "sortīrī",
    thirdPart: "sortītus sum",
    meanings: "draw lots, share, select"},
  {entry: "testor",
    infinitive: "testārī",
    thirdPart: "testātus sum",
    meanings: "bear witness, testify"},
  {entry: "tueor",
    infinitive: "tuērī",
    thirdPart: "tūtus sum",
    meanings: "defend, protect"},
  {entry: "ulcīscor",
    infinitive: "ulcīscī",
    thirdPart: "ultus sum",
    meanings: "avenge, take revenge"},
  {entry: "ūtor",
    infinitive: "ūtī",
    thirdPart: "ūsus sum",
    meanings: "use, experience"},
  {entry: "vagor",
    infinitive: "vagārī",
    thirdPart: "vagātus sum",
    meanings: "wander, roam, ramble"},
  {entry: "vereor",
    infinitive: "verērī",
    thirdPart: "veritus sum",
    meanings: "fear, respect, be in awe (of)"},
  {entry: "vēscor",
    infinitive: "vēscī",
    thirdPart: "---",
    meanings: "feed upon"},
  {entry: "videor",
    infinitive: "vidērī",
    thirdPart: "vīsus sum",
    meanings: "seem, appear"}
]

let verbsLength = verbsReview6.length;

function displayVerbs() {
  let j = 1;
  let html = `<ol style="1" start="1">`;
  let iteration = "";

  for (let i = 0; i < verbsLength; i++) {
    iteration += `<div id="verb-item-${j}" class="container-flex"><li id="li-${j}">`;
    iteration += `<div id="top-row-${j}" class="row">`;
    iteration += `<span id="latin-span-${j}" style="width: 100%; margin-left: 20px"><strong>${verbsReview6[i].entry}</strong><br/> `;
    iteration += `<input id="second-part-${j}" type="text" size="15" placeholder="(present infinitive)">`
    iteration += `<span id="infinitive-${j}" class="vocab-span" style="font-weight: bold">${verbsReview6[i].infinitive}</span><br/>`
    iteration += `<input id="third-part-${j}" type="text" size="15" placeholder="(third part)">`
    iteration += `<span id="perfect-${j}" class="vocab-span" style="font-weight: bold">${verbsReview6[i].thirdPart}</span><br/>`
    iteration += `<input id="meaning-part-${j}" type="text" size="25" placeholder="(meanings)">`
    iteration += `<span id="meaning-${j}" class="vocab-span""><em>${verbsReview6[i].meanings}</em></span><br/>`
    iteration += `<span id="button-span-${j}" class="col-1"><button id="reveal${j}" class="reveal-vocab btn btn-outline-dark" style="margin-top: .5em">--></button></span> `;
    iteration += `</div></li></div><hr/>`;
    j++;
  }

  html += iteration;
  html += "</ol>";
  return html;
}
