const adjectivesReview5 = [
  {entry: "acūtus, -a, -um",
    genitive: "acūtī",
    dative: "acūtō",
    meanings: "sharp, pointy"},
  {entry: "aliquis, aliquid",
    genitive: "alicuius",
    dative: "alicui",
    meanings: "someone, something"},
  {entry: "alius, alia, aliud",
    genitive: "alterīus",
    dative: "aliī",
    meanings: "another"},
  {entry: "alter, altera, alterum",
    genitive: "alterīus",
    dative: "alterī",
    meanings: "the other (of two)"},
  {entry: "crēdībilis, -is, -e",
    genitive: "crēdībilis",
    dative: "crēdībilī",
    meanings: "believable"},
  {entry: "domesticus, -a, -um",
    genitive: "domesticī",
    dative: "domesticō",
    meanings: "domestic, relating to the home"},
  {entry: "faciālis, -is, -e",
    genitive: "faciālis",
    dative: "faciālī",
    meanings: "facial, on the surface"},
  {entry: "fētōsus, -a, -um",
    genitive: "fētōsī",
    dative: "fētōsō",
    meanings: "productive, fertile"},
  {entry: "fīdus, -a, -um",
    genitive: "fīdī",
    dative: "fīdō",
    meanings: "faithful, trustworthy"},
  {entry: "frūctifer, -era, -erum",
    genitive: "frūctiferī",
    dative: "frūctiferō",
    meanings: "fruit-bearing"},
  {entry: "gelidus, -a, -um",
    genitive: "gelidī",
    dative: "gelidō",
    meanings: "frosty, chilly, icy"},
  {entry: "īdem, eadem, idem",
    genitive: "eiusdem",
    dative: "eīdem",
    meanings: "the same"},
  {entry: "ipse, ipsa, ipsum",
    genitive: "ipsīus",
    dative: "ipsī",
    meanings: "-self/-selves (intensive pronoun)"},
  {entry: "is, ea, id",
    genitive: "eius",
    dative: "eī",
    meanings: "he/she/it/they, this, that"},
  {entry: "nātālis, -is, -e",
    genitive: "nātālis",
    dative: "nātālī",
    meanings: "natal, relating to birth"},
  {entry: "neuter, neutra, neutrum",
    genitive: "neutrīus",
    dative: "neutrī",
    meanings: "neither (of two)"},
  {entry: "nūllus, -a, -um",
    genitive: "nūllīus",
    dative: "nūllī",
    meanings: "no, none"},
  {entry: "quī, quae, quod",
    genitive: "cuius",
    dative: "cui",
    meanings: "who, that, which"},
  {entry: "quis, quid",
    genitive: "cuius",
    dative: "cui",
    meanings: "who? what?"},
  {entry: "quisque, quidque",
    genitive: "cuiusque",
    dative: "cuique",
    meanings: "every, each"},
  {entry: "quisquis, quicquid",
    genitive: "cuiuscuius",
    dative: "cuicui",
    meanings: "any, anyone, anything"},
  {entry: "rabidus, -a, -um",
    genitive: "rabidī",
    dative: "rabidō",
    meanings: "raging, raving, mad"},
  {entry: "sēnsualis, -is, -e",
    genitive: "sēnsualis",
    dative: "sēnsualī",
    meanings: "sensual, related to the senses"},
  {entry: "sēxualis, -is, -e",
    genitive: "sexualis",
    dative: "sēxualī",
    meanings: "sexual, related to sex"},
  {entry: "sōlus, -a, -um",
    genitive: "sōlīus",
    dative: "sōlī",
    meanings: "only, alone"},
  {entry: "speciālis, -is, -e",
    genitive: "speciālis",
    dative: "speciālī",
    meanings: "specific, related to appearance"},
  {entry: "sinuōsus, -a, -um",
    genitive: "sinuōsī",
    dative: "sinuōsō",
    meanings: "curved, curvy"},
  {entry: "spīrituālis, -is, -e",
    genitive: "spīrituālis",
    dative: "spīrituālī",
    meanings: "spiritual, related to spirit"},
  {entry: "tortuōsus, -a, -um",
    genitive: "tortuōsī",
    dative: "tortuōsō",
    meanings: "twisted, winding"},
  {entry: "tōtus, -a, -um",
    genitive: "tōtīus",
    dative: "tōtī",
    meanings: "all, the whole"},
  {entry: "trībālis, -is, -e",
    genitive: "trībālis",
    dative: "trībālī",
    meanings: "tribal, related to a tribe"},
  {entry: "ūllus, -a, -um",
    genitive: "ūllīus",
    dative: "ūllī",
    meanings: "some, any"},
  {entry: "ūsuālis, -is, -e",
    genitive: "ūsuālis",
    dative: "ūsuālī",
    meanings: "customary, usual, related to use or experience"},
  {entry: "uter, utra, utrum",
    genitive: "utrīus",
    dative: "utrī",
    meanings: "either (of two)"},
  {entry: "uterque, utraque, utrumque",
    genitive: "utrīusque",
    dative: "utrīque",
    meanings: "each (of two)"}
]

let adjectivesLength = adjectivesReview5.length;

function displayadjectives() {
  let j = 1;
  let html = `<ol style="1" start="${j}">`;
  let iteration = "";

  for (let i = 0; i < adjectivesLength; i++) {
    iteration += `<div id="adjective-item-${j}" class="container-flex"><li id="li-${j}">`;
    iteration += `<div id="top-row-${j}" class="row">`
    iteration += `<span id="latin-span-${j}" style="width: 100%; margin-left: 20px"><strong>${adjectivesReview5[i].entry}</strong></span>`;
    iteration += `<span id="input-span-${j}" style="width: 100%; margin-left: 20px"><input id="genitive-${j}" type="text" size="15" placeholder="(Genitive)"> `
    iteration += `<input id="dative-${j}" type="text" size="15" placeholder="(Dative)"> `
    iteration += `<input id="meaning-${j}" type="text" size="25" placeholder="(meanings)"></span>`
    iteration += `<span id="button-span-${j}" class="col-1"><button id="reveal${j}" class="reveal-vocab btn btn-outline-dark" style="margin-top: .5em">--></button></span> `;
    iteration += `<span id="answer-span-${j}" style="display: none; margin-top: .5em; margin-left: 2em"><strong>${adjectivesReview5[i].genitive},
      ${adjectivesReview5[i].dative}</strong> — <em>${adjectivesReview5[i].meanings}</em></span>`;
    iteration += `</div></li></div><hr/>`;

    j++;
  }


  html += iteration;
  html += "</ol>";
  return html;
}
