const verbsReview5 = [
  {entry: "accipiō",
  infinitive: "accipere",
  thirdPart: "accēpī",
  supine: "acceptum",
  meanings: "accept, receive"},
  {entry: "adveniō",
    infinitive: "advenīre",
    thirdPart: "advēnī",
    supine: "adventum",
    meanings: "come toward, arrive"},
  {entry: "aedificō",
    infinitive: "aedificāre",
    thirdPart: "aedificāvī",
    supine: "aedificātum",
    meanings: "build"},
  {entry: "āmittō",
    infinitive: "āmittere",
    thirdPart: "āmīsī",
    supine: "āmissum",
    meanings: "lose, send away"},
  {entry: "apparō",
    infinitive: "apparāre",
    thirdPart: "apparāvī",
    supine: "apparātum",
    meanings: "prepare, equip, provide (for)"},
  {entry: "cadō",
    infinitive: "cadere",
    thirdPart: "cecidī",
    supine: "cāsum",
    meanings: "fall, happen"},
  {entry: "caedō",
    infinitive: "caedere",
    thirdPart: "cecīdī",
    supine: "caesum",
    meanings: "cut, cut down"},
  {entry: "cēnseō",
    infinitive: "cēnsēre",
    thirdPart: "cēnsī",
    supine: "censsum",
    meanings: "count, value, estimate"},
  {entry: "coeō",
    infinitive: "coīre",
    thirdPart: "coīvī",
    supine: "coitum",
    meanings: "assemble, unite, go together"},
  {entry: "cognōscō",
    infinitive: "cognōscere",
    thirdPart: "cognōvī",
    supine: "cognitum",
    meanings: "learn, be aware, recognize, get to know"},
  {entry: "committō",
    infinitive: "committere",
    thirdPart: "commīsī",
    supine: "commissum",
    meanings: "commit, begin, carry on"},
  {entry: "cōnficiō",
    infinitive: "cōnficere",
    thirdPart: "cōnfēcī",
    supine: "cōnfectum",
    meanings: "accomplish, execute"},
  {entry: "cōniciō",
    infinitive: "cōnicere",
    thirdPart: "cōniēcī",
    supine: "cōniectum",
    meanings: "hurl, fling"},
  {entry: "cōnscrībō",
    infinitive: "cōnscrībere",
    thirdPart: "cōnscrīpsī",
    supine: "cōnscrīptum",
    meanings: "enlist, draft (into the military)"},
  {entry: "cōnsentiō",
    infinitive: "cōnsentīre",
    thirdPart: "cōnsēnsī",
    supine: "cōnsēnsum",
    meanings: "agree, give permission"},
  {entry: "cōnstituō",
    infinitive: "cōnstituere",
    thirdPart: "cōnstituī",
    supine: "cōnstitūtum",
    meanings: "set up, decide, determine"},
  {entry: "crēdō",
    infinitive: "crēdere",
    thirdPart: "crēdidī",
    supine: "crēditum",
    meanings: "believe, trust"},
  {entry: "dēcipiō",
    infinitive: "dēcipere",
    thirdPart: "dēcēpī",
    supine: "dēceptum",
    meanings: "entrap, deceive"},
  {entry: "dēficiō",
    infinitive: "dēficere",
    thirdPart: "dēfēcī",
    supine: "dēfectum",
    meanings: "exhaust, deplete, forsake"},
  {entry: "exerceō",
    infinitive: "exercēre",
    thirdPart: "exercuī",
    supine: "exercitum",
    meanings: "train, exercise"},
  {entry: "fīdō",
    infinitive: "fīdere",
    thirdPart: "fīsus sum",
    supine: "---",
    meanings: "trust, have faith (in)"},
  {entry: "impediō",
    infinitive: "impedīre",
    thirdPart: "impedīvī",
    supine: "impedītum",
    meanings: "impeded, hinder, obstruct"},
  {entry: "incipiō",
    infinitive: "incipere",
    thirdPart: "incēpī",
    supine: "inceptum",
    meanings: "begin, take on"},
  {entry: "indicō",
    infinitive: "indicāre",
    thirdPart: "indicāvī",
    supine: "indicātum",
    meanings: "point (out), indicate"},
  {entry: "instruō",
    infinitive: "instrure",
    thirdPart: "instrūxī",
    supine: "instrūctum",
    meanings: "instruct, teach, build onto"},
  {entry: "intellegō",
    infinitive: "intellegere",
    thirdPart: "intellēxī",
    supine: "intellēctum",
    meanings: "understand, learn"},
  {entry: "interficiō",
    infinitive: "interficere",
    thirdPart: "interfēcī",
    supine: "interfectum",
    meanings: "kill, destroy"},
  {entry: "inveniō",
    infinitive: "invenīre",
    thirdPart: "invenī",
    supine: "inventum",
    meanings: "find, discover, come upon"},
  {entry: "iūdicō",
    infinitive: "iūdicāre",
    thirdPart: "iūdicāvī",
    supine: "iūdicātum",
    meanings: "judge, examine, condemn"},
  {entry: "levō",
    infinitive: "levāre",
    thirdPart: "levāvī",
    supine: "levātum",
    meanings: "live, lighten, ease"},
  {entry: "magistrō",
    infinitive: "magistrāre",
    thirdPart: "magistrāvī",
    supine: "magistrātum",
    meanings: "direct, guide, teach"},
  {entry: "occidō",
    infinitive: "occidere",
    thirdPart: "occidī",
    supine: "occāsum",
    meanings: "fall, die (in battle)"},
  {entry: "occīdō",
    infinitive: "occīdere",
    thirdPart: "occīdī",
    supine: "occīsum",
    meanings: "cut down, kill (in battle)"},
  {entry: "pereō",
    infinitive: "perīre",
    thirdPart: "perīvī",
    supine: "perītum",
    meanings: "perish, die, go through"},
  {entry: "perficiō",
    infinitive: "perficere",
    thirdPart: "perfēcī",
    supine: "perfectum",
    meanings: "complete, do thoroughly"},
  {entry: "persuādeō",
    infinitive: "persuādēre",
    thirdPart: "persuāsī",
    supine: "persuāsum",
    meanings: "persuade"},
  {entry: "prōmittō",
    infinitive: "prōmittere",
    thirdPart: "prōmīsī",
    supine: "prōmissum",
    meanings: "promise, send forth"},
  {entry: "prōscrībō",
    infinitive: "prōscrībere",
    thirdPart: "prōscrīpsī",
    supine: "prōscrīptum",
    meanings: "publish, ban, outlaw"},
  {entry: "quiescō",
    infinitive: "quiescere",
    thirdPart: "quiēvī",
    supine: "quiētum",
    meanings: "rest, be calm"},
  {entry: "rabiō",
    infinitive: "rabere",
    thirdPart: "---",
    supine: "---",
    meanings: "rage, go mad"},
  {entry: "secō",
    infinitive: "secāre",
    thirdPart: "secuī",
    supine: "sectum",
    meanings: "cut off, divide"},
  {entry: "suscipiō",
    infinitive: "suscipere",
    thirdPart: "suscēpī",
    supine: "susceptum",
    meanings: "undertake, assume"},
  {entry: "torqueō",
    infinitive: "torquēre",
    thirdPart: "torsī",
    supine: "tortum",
    meanings: "twist, wind, spin"},
  {entry: "vastō",
    infinitive: "vastāre",
    thirdPart: "vastāvī",
    supine: "vastātum",
    meanings: "destroy, devastate"},
  {entry: "vinciō",
    infinitive: "vincīre",
    thirdPart: "vīnxī",
    supine: "vīnctum",
    meanings: "bind, fetter, fasten"}
]

let verbsLength = verbsReview5.length;

function displayVerbs() {
  let j = 1;
  let html = `<ol style="1" start="${j}">`;
  let iteration = "";

  for (let i = 0; i < verbsLength; i++) {
    iteration += `<div id="verb-item-${j}" class="container-flex"><li id="li-${j}">`;
    iteration += `<div id="top-row-${j}" class="row">`
    iteration += `<span id="latin-span-${j}" style="width: 100%; margin-left: 20px"><strong>${verbsReview5[i].entry}, ${verbsReview5[i].infinitive}, </strong> `;
    iteration += `<input id="third-part-${j}" type="text" size="15" placeholder="(third part)"> `
    iteration += `<input id="fourth-part-${j}" type="text" size="15" placeholder="(supine)"> `
    iteration += `<input id="meaning-${j}" type="text" size="25" placeholder="(meanings)"><br/>`
    iteration += `<span id="button-span-${j}" class="col-1"><button id="reveal${j}" class="reveal-vocab btn btn-outline-dark" style="margin-top: .5em">--></button></span> `;
    iteration += `<span id="answer-span-${j}" style="display: none; margin-top: .5em"><strong>${verbsReview5[i].thirdPart}, `;
    iteration += `${verbsReview5[i].supine}</strong>`;
    iteration += ` — <em>${verbsReview5[i].meanings}</em></span>`;
    iteration += `</div></li></div><hr/>`;
    j++;
  }

  html += iteration;
  html += "</ol>";
  return html;
}
