const people5 = [
  {entry: "aciēs",
    caseNumber: "Abl. pl.",
    gender: "f.",
    inflection: "aciēbus",
    meanings: "battle line"},
  {entry: "aedifex",
    caseNumber: "Acc. pl.",
    gender: "u.",
    inflection: "aedificēs",
    meanings: "builder"},
  {entry: "aedīlis",
    caseNumber: "Gen. pl.",
    gender: "u.",
    inflection: "aedīlium",
    meanings: "public works commissioner"},
  {entry: "artifex",
    caseNumber: "Nom. pl.",
    gender: "u.",
    inflection: "artificēs",
    meanings: "artist, artisan"},
  {entry: "augur",
    caseNumber: "Gen. pl.",
    gender: "u.",
    inflection: "augurum",
    meanings: "priest, watcher of birds"},
  {entry: "auspex",
    caseNumber: "Abl. pl.",
    gender: "u.",
    inflection: "auspicibus",
    meanings: "priest, watcher of birds"},
  {entry: "carnifex",
    caseNumber: "Dat. s.",
    gender: "u.",
    inflection: "carnificī",
    meanings: "butcher"},
  {entry: "centuria",
    caseNumber: "Dat. pl.",
    gender: "f.",
    inflection: "centuriīs",
    meanings: "century, group of 100, battle company"},
  {entry: "eques",
    caseNumber: "Voc. s.",
    gender: "u.",
    inflection: "eques",
    meanings: "horseman, knight; cavalry (pl.)"},
  {entry: "equitātus",
    caseNumber: "Gen. s.",
    gender: "n.",
    inflection: "equitātūs",
    meanings: "cavalry unit"},
  {entry: "exercitus",
    caseNumber: "Acc. pl.",
    gender: "m.",
    inflection: "exercitūs",
    meanings: "trained army"},
  {entry: "fētus",
    caseNumber: "Acc. s.",
    gender: "m.",
    inflection: "fētum",
    meanings: "offspring, bearing forth"},
  {entry: "haruspex",
    caseNumber: "Dat. pl.",
    gender: "u.",
    inflection: "haruspicibus",
    meanings: "priest, examiner of entrails"},
  {entry: "hospes",
    caseNumber: "Gen. pl.",
    gender: "u.",
    inflection: "hospitum",
    meanings: "guest, host"},
  {entry: "iūdex",
    caseNumber: "Dat. s.",
    gender: "u.",
    inflection: "iūdicī",
    meanings: "judge, arbiter"},
  {entry: "lēgātus",
    caseNumber: "Dat. s.",
    gender: "u.",
    inflection: "lēgātō",
    meanings: "lieutenant, envoy"},
  {entry: "magistrātus",
    caseNumber: "Nom. pl.",
    gender: "u.",
    inflection: "magistrātūs",
    meanings: "magistrate, magistracy"},
  {entry: "manipulus",
    caseNumber: "Abl. pl.",
    gender: "m.",
    inflection: "manipulīs",
    meanings: "handful, brigade (30-50 soldiers)"},
  {entry: "mīles",
    caseNumber: "Gen. s.",
    gender: "u.",
    inflection: "mīlitis",
    meanings: "soldier"},
  {entry: "opifex",
    caseNumber: "Voc. pl.",
    gender: "u.",
    inflection: "opificēs",
    meanings: "worker, craftsperson"},
  {entry: "pedes",
    caseNumber: "Acc. s.",
    gender: "u.",
    inflection: "peditem",
    meanings: "foot-soldier; infantry (pl.)"},
  {entry: "pontifex",
    caseNumber: "Dat. s.",
    gender: "u.",
    inflection: "pontificī",
    meanings: "priest, high priest"},
  {entry: "prōgeniēs",
    caseNumber: "Voc. s.",
    gender: "f.",
    inflection: "prōgeniēs",
    meanings: "offspring, progeny, descendants"},
  {entry: "prōgenitor/-trīx",
    caseNumber: "Voc. s.",
    gender: "u.",
    inflection: "prōgenitor/-trīx",
    meanings: "ancestor, foreparent"},
  {entry: "sacerdōs",
    caseNumber: "Acc. s.",
    gender: "u.",
    inflection: "sacerdōtem",
    meanings: "priest"},
  {entry: "tribūnus",
    caseNumber: "Abl. pl.",
    gender: "u.",
    inflection: "tribūnīs",
    meanings: "tribal chief, tribal councilmember"},
  {entry: "tribus",
    caseNumber: "Voc. s.",
    gender: "m.",
    inflection: "tribus",
    meanings: "tribe, ethnic origin"}
]

const nha5 = [
  {entry: "ariēs",
    caseNumber: "Acc. pl.",
    gender: "m.",
    inflection: "ariētēs",
    meanings: "ram, battering ram"},
  {entry: "bōs",
    caseNumber: "Voc. pl.",
    gender: "u.",
    inflection: "bōvēs",
    meanings: "ox; oxen, cattle (pl.)"},
  {entry: "lepus",
    caseNumber: "Dat. pl.",
    gender: "u./m.",
    inflection: "leporibus",
    meanings: "hare, rabbit"},
  {entry: "mūs",
    caseNumber: "Acc. s.",
    gender: "u.",
    inflection: "mūrem",
    meanings: "mouse, rat"},
  {entry: "testūdō",
    caseNumber: "Abl. pl.",
    gender: "m.",
    inflection: "testlūdinibus",
    meanings: "tortoise; raised-shield battle formation"}
]

const bodyMind5 = [
  {entry: "cornū",
    caseNumber: "Gen. s.",
    gender: "n.",
    inflection: "cornūs",
    meanings: "horn; wing of a army"},
  {entry: "digitus",
    caseNumber: "Nom. pl.",
    gender: "m.",
    inflection: "digitī",
    meanings: "finger, toe (digitus pedis)"},
  {entry: "ēsuriēs",
    caseNumber: "Acc. s.",
    gender: "f.",
    inflection: "ēsuriem",
    meanings: "hunger"},
  {entry: "faciēs",
    caseNumber: "Dat. pl.",
    gender: "f.",
    inflection: "faciēbus",
    meanings: "face, surface"},
  {entry: "genū",
    caseNumber: "Voc. s.",
    gender: "n.",
    inflection: "genū",
    meanings: "knee"},
  {entry: "index",
    caseNumber: "Dat. pl.",
    gender: "m.",
    inflection: "indicibus",
    meanings: "pointer, indicator, index finger"},
  {entry: "manus",
    caseNumber: "Voc. pl.",
    gender: "f.",
    inflection: "manūs",
    meanings: "hand"},
  {entry: "oculus",
    caseNumber: "Gen. pl.",
    gender: "m.",
    inflection: "oculōrum",
    meanings: "eye"},
  {entry: "pollex",
    caseNumber: "Acc. pl.",
    gender: "m.",
    inflection: "pollicēs",
    meanings: "thumb; big toe (pollex pedis)"},
  {entry: "pēs",
    caseNumber: "Acc. s.",
    gender: "m.",
    inflection: "pedem",
    meanings: "foot"},
  {entry: "sanguis",
    caseNumber: "Abl. s.",
    gender: "m.",
    inflection: "sanguine",
    meanings: "blood"},
  {entry: "sexus",
    caseNumber: "Abl. pl.",
    gender: "m.",
    inflection: "sexibus",
    meanings: "anatomical sex"},
  {entry: "spīritus",
    caseNumber: "Gen. pl.",
    gender: "m.",
    inflection: "spīrituum",
    meanings: "spirit; breath"},
  {entry: "vultus",
    caseNumber: "Dat. s.",
    gender: "m.",
    inflection: "vultuī",
    meanings: "facial expression, countenance"}
]

const naturalWorld5 = [
  {entry: "flōs",
    caseNumber: "Nom. pl.",
    gender: "m.",
    inflection: "florēs",
    meanings: "flower, bloom"},
  {entry: "frūctus",
    caseNumber: "Voc. s.",
    gender: "m.",
    inflection: "frūctus",
    meanings: "fruit, end-product; enjoyment"},
  {entry: "gelū",
    caseNumber: "Acc. s.",
    gender: "n.",
    inflection: "gelū",
    meanings: "frost"},
  {entry: "iūgum",
    caseNumber: "Gen. pl.",
    gender: "n.",
    inflection: "iūgōrum",
    meanings: "yoke; mountain ridge"},
  {entry: "lacus",
    caseNumber: "Abl. s.",
    gender: "m.",
    inflection: "lacū",
    meanings: "lake, pond"},
  {entry: "lapis",
    caseNumber: "Abl. pl.",
    gender: "m.",
    inflection: "lapide",
    meanings: "stone"},
  {entry: "pīnus",
    caseNumber: "Acc. pl.",
    gender: "f.",
    inflection: "pīnūs",
    meanings: "pine tree"},
  {entry: "quercus",
    caseNumber: "Dat. s.",
    gender: "f.",
    inflection: "quercuī",
    meanings: "oak tree"},
  {entry: "saxum",
    caseNumber: "Abl. pl.",
    gender: "n.",
    inflection: "saxīs",
    meanings: "rock"},
  {entry: "sinus",
    caseNumber: "Gen. s.",
    gender: "m.",
    inflection: "curve, lap; bay, gulf",
    meanings: "sinūs"},
  {entry: "tempestās",
    caseNumber: "Voc. pl.",
    gender: "f.",
    inflection: "tempestātēs",
    meanings: "storm, weather"}
]

const buildings5 = [
  {entry: "aedis",
    caseNumber: "Gen. pl.",
    gender: "f.",
    inflection: "aedium",
    meanings: "temple, shrine, public building"},
  {entry: "castra",
    caseNumber: "Dat. pl.",
    gender: "n.",
    inflection: "castrīs",
    meanings: "camp, barracks"},
  {entry: "complūvium",
    caseNumber: "Abl. s.",
    gender: "n.",
    inflection: "complūviō",
    meanings: "opening in the roof of an atrium"},
  {entry: "domicilium",
    caseNumber: "Acc. pl.",
    gender: "n.",
    inflection: "domicilia",
    meanings: "housing unit"},
  {entry: "domus",
    caseNumber: "Locative s.",
    gender: "f.",
    inflection: "domī",
    meanings: "city house, home"},
  {entry: "implūvium",
    caseNumber: "Abl. pl.",
    gender: "n.",
    inflection: "implūviīs",
    meanings: "rain basin in an atrium"
  }
]

const commonObjects5 = [
  {entry: "acus",
    caseNumber: "Acc. s.",
    gender: "n.",
    inflection: "acum",
    meanings: "needle, sharp point"},
  {entry: "arcus",
    caseNumber: "Nom. pl.",
    gender: "m.",
    inflection: "arcūs",
    meanings: "bow, curve, rainbow"},
  {entry: "arma",
    caseNumber: "Dat. s.",
    gender: "n.",
    inflection: "armīs",
    meanings: "arms, armor, weaponry"},
  {entry: "apparātus",
    caseNumber: "Voc. pl.",
    gender: "m.",
    inflection: "apparātūs",
    meanings: "equipment"},
  {entry: "ballista",
    caseNumber: "Abl. s.",
    gender: "f.",
    inflection: "ballistā",
    meanings: "artillery device for launching rocks and stones"},
  {entry: "catapulta",
    caseNumber: "Acc. pl.",
    gender: "f.",
    inflection: "catapultīs",
    meanings: "artillery device for launching large spears"},
  {entry: "hasta",
    caseNumber: "Dat. s.",
    gender: "f.",
    inflection: "hastae",
    meanings: "pike, lance, spear"},
  {entry: "impedīmentum",
    caseNumber: "Abl. s.",
    gender: "n.",
    inflection: "impedīmentō",
    meanings: "hindrance; baggage (pl.)"},
  {entry: "pīlum",
    caseNumber: "Abl. pl.",
    gender: "n.",
    inflection: "pīlīs",
    meanings: "throwing spear, javelin"},
  {entry: "tormentum",
    caseNumber: "Gen. pl.",
    gender: "n.",
    inflection: "tormentōrum",
    meanings: "siege engine; torture"},
  {entry: "vīctus",
    caseNumber: "Gen. s.",
    gender: "m.",
    inflection: "vīctūs",
    meanings: "nourishment"},
  {entry: "vinculum",
    caseNumber: "Gen. s.",
    gender: "n.",
    inflection: "vinculī",
    meanings: "chain, fetter, binding"}
]

const activities5 = [
  {entry: "adventus",
    caseNumber: "Gen. pl.",
    gender: "m.",
    inflection: "adventuum",
    meanings: "arrival, approach"},
  {entry: "bellum",
    caseNumber: "Gen. s.",
    gender: "n.",
    inflection: "bellī",
    meanings: "war"},
  {entry: "cēnsus",
    caseNumber: "Acc. s.",
    gender: "m.",
    inflection: "cēnsum",
    meanings: "counting, population count"},
  {entry: "coitus",
    caseNumber: "Acc. s.",
    gender: "m.",
    inflection: "coitum",
    meanings: "sexual intercourse"},
  {entry: "cursus",
    caseNumber: "Dat. pl.",
    gender: "m.",
    inflection: "cursibus",
    meanings: "course, run, running"},
  {entry: "dictum",
    caseNumber: "Nom. pl.",
    gender: "n.",
    inflection: "dicta",
    meanings: "saying, proverb, command"},
  {entry: "factum",
    caseNumber: "Acc. pl.",
    gender: "n.",
    inflection: "dicta",
    meanings: "deed, accomplishment"},
  {entry: "fuga",
    caseNumber: "Abl. pl.",
    gender: "f.",
    inflection: "fugīs",
    meanings: "flight, escape"},
  {entry: "gradus",
    caseNumber: "Dat. s.",
    gender: "m.",
    inflection: "graduī",
    meanings: "step, degree, rank"},
  {entry: "laus",
    caseNumber: "Voc. s.",
    gender: "f.",
    inflection: "laus",
    meanings: "praise, honor"},
  {entry: "nātus",
    caseNumber: "Voc. pl.",
    gender: "m.",
    inflection: "nātūs",
    meanings: "birth"},
  {entry: "passus",
    caseNumber: "Acc. pl.",
    gender: "m.",
    inflection: "passūs",
    meanings: "pace, two steps"},
  {entry: "proelium",
    caseNumber: "Dat. s.",
    gender: "n.",
    inflection: "proeliō",
    meanings: "battle"},
  {entry: "quiēs",
    caseNumber: "Dat. pl.",
    gender: "f.",
    inflection: "quiētibus",
    meanings: "rest, calm, quiet"},
  {entry: "requiēs",
    caseNumber: "Gen. s.",
    gender: "f.",
    inflection: "requiētis",
    meanings: "rest, quiet"},
  {entry: "rīsus",
    caseNumber: "Abl. s.",
    gender: "m.",
    inflection: "rīsū",
    meanings: "laughter"},
  {entry: "sectiō",
    caseNumber: "Abl. pl.",
    gender: "f.",
    inflection: "sectiōnibus",
    meanings: "section, division, cutting"},
  {entry: "sēnsus",
    caseNumber: "Gen. pl.",
    gender: "m.",
    inflection: "sēnsuum",
    meanings: "sense, feeling"},
  {entry: "stātus",
    caseNumber: "Dat. s.",
    gender: "m.",
    inflection: "stātuī",
    meanings: "status, standing"},
  {entry: "tortiō",
    caseNumber: "Acc. pl..",
    gender: "f.",
    inflection: "tortiōnēs",
    meanings: "twisting, winding, spinning"},
  {entry: "ūsus",
    caseNumber: "Gen. s.",
    gender: "m.",
    inflection: "ūsūs",
    meanings: "use, experience"}
]

const miscellany5 = [
  {entry: "cariēs",
    caseNumber: "Nom. pl.",
    gender: "f.",
    inflection: "cariēs",
    meanings: "rot, decay"},
  {entry: "cāsus",
    caseNumber: "Abl. pl.",
    gender: "m.",
    inflection: "cāsibus",
    meanings: "case, occurrence, fall"},
  {entry: "dolor",
    caseNumber: "Acc. pl.",
    gender: "n.",
    inflection: "dolōrēs",
    meanings: "pain, grief"},
  {entry: "fīdēs",
    caseNumber: "Dat. pl.",
    gender: "f.",
    inflection: "fīdēbus",
    meanings: "faith, trust"},
  {entry: "mōs",
    caseNumber: "Gen. pl.",
    gender: "m.",
    inflection: "mōrum",
    meanings: "custom, behavior"},
  {entry: "perīculum",
    caseNumber: "Voc. pl.",
    gender: "n.",
    inflection: "perīcula",
    meanings: "danger, risk"},
  {entry: "poena",
    caseNumber: "Dat. s.",
    gender: "f.",
    inflection: "poenae",
    meanings: "punishment, penalty"},
  {entry: "potestās",
    caseNumber: "Gen. s.",
    gender: "f.",
    inflection: "potestātis",
    meanings: "power, strength"},
  {entry: "rabiēs",
    caseNumber: "Acc. s.",
    gender: "f.",
    inflection: "rabiem",
    meanings: "rage, madness"},
  {entry: "rēs",
    caseNumber: "Abl. s.",
    gender: "f.",
    inflection: "rē",
    meanings: "thing, matter, affair"},
  {entry: "seriēs",
    caseNumber: "Abl. pl.",
    gender: "f.",
    inflection: "seriēbus",
    meanings: "row, sequence, series"},
  {entry: "speciēs",
    caseNumber: "Voc. s.",
    gender: "f.",
    inflection: "speciēs",
    meanings: "appearance"},
  {entry: "spēs",
    caseNumber: "Gen. s.",
    gender: "f.",
    inflection: "speī",
    meanings: "hope"},
  {entry: "voluntās",
    caseNumber: "Gen. s.",
    gender: "f.",
    inflection: "voluntātis",
    meanings: "desire, free will"},
  {entry: "voluptās",
    caseNumber: "Acc. pl.",
    gender: "f.",
    inflection: "voluptātēs",
    meanings: "pleasure, delight; pleasure seeking"}
]

let peopleLength = people5.length;
let nhaLength = nha5.length;
let bodyMindLength = bodyMind5.length;
let naturalWorldLength = naturalWorld5.length;
let buildingsLength = buildings5.length;
let commonObjLength = commonObjects5.length;
let activitiesLength = activities5.length;
let miscLength = miscellany5.length;
let part2Length = peopleLength + nhaLength;
let part3Length = part2Length + bodyMindLength;
let part4Length = part3Length + naturalWorldLength;
let part5Length = part4Length + buildingsLength;
let part6Length = part5Length + commonObjLength;
let part7Length = part6Length + activitiesLength;
let nounsLength = part7Length + miscLength;

function displayNouns(a,b,c) {
  let html = `<ol style="1" start="${a}">`;
  let iteration = "";
  let j = a;
  for (let i = 0; i < b; i++) {
    iteration += `<li>`;
    iteration += `<span id="noun-span-${j}" class="col-6">${c[i].entry}—${c[i].caseNumber}</span><br/>`;
    iteration += `<span id="form-span-${j}" class="col-6">Form: </span><input id="input${j}" type="text" size="12" style="margin-left: 1em"><br/>`
    iteration += `<span id="gender-span-${j}" class="col-6">Gender: </span><input id="input${j}" type="text" size="3" style="margin-left: 1em"><br/>`
    iteration += `<span id="meaning-span-${j}" class="col-6">Meanings: </span><input id="input${j}" type="text" size="30" style="margin-left: 1em"><br/>`
    iteration += `<span id="button-span-${j}" class="col-1"><button id="reveal${j}" class="reveal-vocab btn btn-outline-dark">--></button></span> `;
    iteration += `<span id="vocab${j}" class="vocab-span col-6"><strong>${c[i].inflection}</strong> |
        ${c[i].gender} | <em>${c[i].meanings}</em></span><hr/></li>`;
    j++;
  }
  html += iteration + "</ol>";
  return html;
}

