const vocab3 = [
  {latin: "-ne?",
  english: "(particle introducing a yes/no question)"},
  {latin: "-que",
    english: "and"},
  {latin: "agricola",
    english: "farmer"},
  {latin: "aurīga",
    english: "charioteer"},
  {latin: "aut",
    english: "or"},
  {latin: "deus/dea",
    english: "god/goddess"},
  {latin: "discipulus/discipula",
    english: "student"},
  {latin: "dominus/domina",
    english: "lord/lady, master/mistress"},
  {latin: "sum, esse",
    english: "to be"},
  {latin: "et",
    english: "and"},
  {latin: "familia",
    english: "family, household"},
  {latin: "fēmina",
    english: "woman"},
  {latin: "fierī",
    english: "to become, to be made"},
  {latin: "fīlius/fīlia",
    english: "son/daughter"},
  {latin: "hīc",
    english: "here, in this place"},
  {latin: "ibi",
    english: "there, in that place"},
  {latin: "incola",
    english: "inhabitant, dweller"},
  {latin: "eō, īre",
    english: "to go"},
  {latin: "magister/magistra",
    english: "teacher, master/mistress"},
  {latin: "nauta",
    english: "sailor"},
  {latin: "nōlō, nōlle",
    english: "not to want, to refuse"},
  {latin: "nōn",
    english: "not"},
  {latin: "nōnne?",
    english: "(expecting a yes answer)"},
  {latin: "num?",
    english: "(expecting a no answer)"},
  {latin: "nunc",
    english: "now, at this time"},
  {latin: "pīrāta",
    english: "pirate"},
  {latin: "poēta",
    english: "poet"},
  {latin: "possum, posse",
    english: "to be able"},
  {latin: "puer/puella",
    english: "child, boy/girl"},
  {latin: "quandō?",
    english: "when?"},
  {latin: "quid?",
    english: "what?"},
  {latin: "quis?",
    english: "who?"},
  {latin: "quō?",
    english: "whither? to what place?"},
  {latin: "scrība",
    english: "scribe, clerk"},
  {latin: "sed",
    english: "but"},
  {latin: "semper",
    english: "always"},
  {latin: "tum",
    english: "then, at that time"},
  {latin: "ubi?",
    english: "where? in what place?"},
  {latin: "ubique",
    english: "everywhere"},
  {latin: "volō, velle",
    english: "to want"},
  {latin: "vir",
    english: "man"},
]

const vocab6 = [
  {latin: "ambulō, ambulāre",
    english: "to walk"},
  {latin: "clāmō, clāmāre",
    english: "to shout"},
  {latin: "errō, errāre",
    english: "to wander, to make a mistake"},
  {latin: "habitō, habitāre",
    english: "to live, to dwell"},
  {latin: "lābōrō, lābōrāre",
    english: "to work, to suffer"},
  {latin: "ōrō, ōrāre",
    english: "to pray, to ask, to speak persuasively"},
  {latin: "pugnō, pugnāre",
    english: "to fight"},
  {latin: "stō, stāre",
    english: "to stand"},
  {latin: "caper/capra",
    english: "goat"},
  {latin: "equus/equa",
    english: "horse"},
  {latin: "taurus",
    english: "bull"},
  {latin: "vacca",
    english: "cow"},
  {latin: "ager",
    english: "field, farm"},
  {latin: "campus",
    english: "field, plain, battlefield"},
  {latin: "casa",
    english: "cottage, hut"},
  {latin: "īnsula",
    english: "island, apartment house"},
  {latin: "Ītālia",
    english: "Italy"},
  {latin: "liber",
    english: "book"},
  {latin: "lūdus",
    english: "game, school"},
  {latin: "Rōma",
    english: "Rome"},
  {latin: "prōvincia",
    english: "province"},
  {latin: "terra",
    english: "land, earth, country"},
  {latin: "via",
    english: "road, way"},
  {latin: "vīlla",
    english: "farmhouse, manor"},
  {latin: "vīta",
    english: "life"},
  {latin: "adōrō, adōrāre",
    english: "to worship, to pray to"},
  {latin: "amō, amāre",
    english: "to love, to like"},
  {latin: "iuvō, iuvāre",
    english: "to help"},
  {latin: "laudō, laudāre",
    english: "to praise"},
  {latin: "līberō, līberāre",
    english: "to free, to set free"},
  {latin: "occupō, occupāre",
    english: "to seize"},
  {latin: "parō, parāre",
    english: "to prepare"},
  {latin: "portō, portāre",
    english: "to carry"},
  {latin: "salūtō, salūtāre",
    english: "to greet"},
  {latin: "servō, servāre",
    english: "to keep, to save, to guard"},
  {latin: "spectō, spectāre",
    english: "to watch, to look at"},
  {latin: "vocō, vocāre",
    english: "to call"},
  {latin: "in",
    english: "in, on, into, onto, against"},
  {latin: "quem?",
    english: "whom?"}
]

const vocab9 = [
  {latin: "doceō, docēre",
    english: "to teach"},
  {latin: "habeō, habēre",
    english: "to have, to hold"},
  {latin: "iaceō, iacēre",
    english: "to lie (in place)"},
  {latin: "maneō, manēre",
    english: "to stay, to remain"},
  {latin: "moneō, monēre",
    english: "to warn, to advise"},
  {latin: "prohibeō, prohibēre",
    english: "to prevent, to stop"},
  {latin: "rīdeō, ridēre",
    english: "to laugh, to laugh at"},
  {latin: "sedeō, sedēre",
    english: "to sit"},
  {latin: "teneō, tenēre",
    english: "to hold, to have"},
  {latin: "terreō, terrēre",
    english: "to frighten"},
  {latin: "timeō, timēre",
    english: "to fear, to be afraid of"},
  {latin: "videō, vidēre",
    english: "to see"},
  {latin: "equitō, equitāre",
    english: "to ride a horse"},
  {latin: "moveō, movēre",
    english: "to move"},
  {latin: "natō, natāre",
    english: "to swim, to float"},
  {latin: "nāvigō, nāvigāre",
    english: "to sail"},
  {latin: "saltō, saltāre",
    english: "to leap, to dance"},
  {latin: "volō, volāre",
    english: "to fly"},
  {latin: "aqua",
    english: "water"},
  {latin: "culīna",
    english: "kitchen"},
  {latin: "fundus",
    english: "farm, estate, bottomland"},
  {latin: "mūrus",
    english: "wall"},
  {latin: "taberna",
    english: "shop, tavern, inn"},
  {latin: "vīcus",
    english: "village"},
  {latin: "bonus",
    english: "good"},
  {latin: "laetus",
    english: "happy"},
  {latin: "magnus",
    english: "great, large"},
  {latin: "malus",
    english: "bad, evil"},
  {latin: "meus",
    english: "my, mine"},
  {latin: "miser",
    english: "sad, poor, wretched"},
  {latin: "multus",
    english: "much"},
  {latin: "multī",
    english: "many"},
  {latin: "noster",
    english: "our, ours"},
  {latin: "parvus",
    english: "small"},
  {latin: "paucī",
    english: "few, a few"},
  {latin: "tuus",
    english: "your, yours (s.)"},
  {latin: "vester",
    english: "your, yours (pl.)"},
  {latin: "Ītālus",
    english: "Italian"},
  {latin: "Lātīnus",
    english: "Latin, from Lazio"},
  {latin: "Rōmānus",
    english: "Roman"},
  {latin: "ā/ab",
    english: "from, away from"},
  {latin: "ad",
    english: "to, toward, for the purpose of"}
]

const allVolumeIVocab = [
  {latin: "-ne?",
    english: "(particle introducing a yes/no question)"},
  {latin: "et, -que",
    english: "and"},
  {latin: "agricola",
    english: "farmer"},
  {latin: "aurīga",
    english: "charioteer"},
  {latin: "aut",
    english: "or"},
  {latin: "deus",
    english: "god"},
  {latin: "dea",
    english: "goddess"},
  {latin: "discipulus/discipula",
    english: "student"},
  {latin: "dominus",
    english: "lord, master"},
  {latin: "domina",
    english: "lady, mistress"},
  {latin: "sum, esse",
    english: "to be"},
  {latin: "familia",
    english: "family, household"},
  {latin: "fēmina",
    english: "woman"},
  {latin: "fierī",
    english: "to become, to be made"},
  {latin: "fīlius",
    english: "son"},
  {latin: "fīlia",
    english: "daughter"},
  {latin: "hīc",
    english: "here, in this place"},
  {latin: "ibi",
    english: "there, in that place"},
  {latin: "incola",
    english: "inhabitant, dweller"},
  {latin: "eō, īre",
    english: "to go"},
  {latin: "magister/magistra",
    english: "teacher"},
  {latin: "nauta",
    english: "sailor"},
  {latin: "nōlō, nōlle",
    english: "not to want, to refuse"},
  {latin: "nōn",
    english: "not"},
  {latin: "nōnne?",
    english: "(expecting a yes answer)"},
  {latin: "num?",
    english: "(expecting a no answer)"},
  {latin: "nunc",
    english: "now, at this time"},
  {latin: "pīrāta",
    english: "pirate"},
  {latin: "poēta",
    english: "poet"},
  {latin: "possum, posse",
    english: "to be able"},
  {latin: "puer",
    english: "child, boy"},
  {latin: "puella",
    english: "girl"},
  {latin: "quandō?",
    english: "when?"},
  {latin: "quid?",
    english: "what?"},
  {latin: "quis?",
    english: "who?"},
  {latin: "quō?",
    english: "whither? to what place?"},
  {latin: "scrība",
    english: "scribe, clerk"},
  {latin: "sed",
    english: "but"},
  {latin: "semper",
    english: "always"},
  {latin: "tum",
    english: "then, at that time"},
  {latin: "ubi?",
    english: "where? in what place?"},
  {latin: "ubique",
    english: "everywhere"},
  {latin: "volō, velle",
    english: "to want"},
  {latin: "vir",
    english: "man"},
  {latin: "ambulō, ambulāre",
    english: "to walk"},
  {latin: "clāmō, clāmāre",
    english: "to shout"},
  {latin: "errō, errāre",
    english: "to wander, to make a mistake"},
  {latin: "habitō, habitāre",
    english: "to live, to dwell"},
  {latin: "lābōrō, lābōrāre",
    english: "to work, to suffer"},
  {latin: "ōrō, ōrāre",
    english: "to pray, to ask, to speak persuasively"},
  {latin: "pugnō, pugnāre",
    english: "to fight"},
  {latin: "stō, stāre",
    english: "to stand"},
  {latin: "caper",
    english: "male goat"},
  {latin: "capra",
    english: "female goat"},
  {latin: "equus",
    english: "male horse"},
  {latin: "equa",
    english: "female horse"},
  {latin: "taurus",
    english: "bull"},
  {latin: "vacca",
    english: "cow"},
  {latin: "ager",
    english: "field (for farming)"},
  {latin: "campus",
    english: "field, plain, battlefield"},
  {latin: "casa",
    english: "cottage, hut"},
  {latin: "īnsula",
    english: "island, apartment house"},
  {latin: "Ītālia",
    english: "Italy"},
  {latin: "liber",
    english: "book"},
  {latin: "lūdus",
    english: "game, school"},
  {latin: "Rōma",
    english: "Rome"},
  {latin: "prōvincia",
    english: "province"},
  {latin: "terra",
    english: "land, earth, country"},
  {latin: "via",
    english: "road, way"},
  {latin: "vīlla",
    english: "farmhouse, manor"},
  {latin: "vīta",
    english: "life"},
  {latin: "adōrō, adōrāre",
    english: "to worship, to pray to"},
  {latin: "amō, amāre",
    english: "to love, to like"},
  {latin: "iuvō, iuvāre",
    english: "to help"},
  {latin: "laudō, laudāre",
    english: "to praise"},
  {latin: "līberō, līberāre",
    english: "to free, to set free"},
  {latin: "occupō, occupāre",
    english: "to seize"},
  {latin: "parō, parāre",
    english: "to prepare"},
  {latin: "portō, portāre",
    english: "to carry"},
  {latin: "salūtō, salūtāre",
    english: "to greet"},
  {latin: "servō, servāre",
    english: "to keep, to save, to guard"},
  {latin: "spectō, spectāre",
    english: "to watch, to look at"},
  {latin: "vocō, vocāre",
    english: "to call"},
  {latin: "in",
    english: "in, on, into, onto, against"},
  {latin: "quem?",
    english: "whom? (Accusative case)"},
  {latin: "doceō, docēre",
    english: "to teach"},
  {latin: "iaceō, iacēre",
    english: "to lie (in place)"},
  {latin: "maneō, manēre",
    english: "to stay, to remain"},
  {latin: "moneō, monēre",
    english: "to warn, to advise"},
  {latin: "prohibeō, prohibēre",
    english: "to prevent, to stop"},
  {latin: "rīdeō, ridēre",
    english: "to laugh, to laugh at"},
  {latin: "sedeō, sedēre",
    english: "to sit"},
  {latin: "habeō, habēre; teneō, tenēre",
    english: "to hold, to have"},
  {latin: "terreō, terrēre",
    english: "to frighten"},
  {latin: "timeō, timēre",
    english: "to fear, to be afraid of"},
  {latin: "videō, vidēre",
    english: "to see"},
  {latin: "equitō, equitāre",
    english: "to ride a horse"},
  {latin: "moveō, movēre",
    english: "to move"},
  {latin: "natō, natāre",
    english: "to swim, to float"},
  {latin: "nāvigō, nāvigāre",
    english: "to sail"},
  {latin: "saltō, saltāre",
    english: "to leap, to dance"},
  {latin: "volō, volāre",
    english: "to fly"},
  {latin: "aqua",
    english: "water"},
  {latin: "culīna",
    english: "kitchen"},
  {latin: "fundus",
    english: "farm, estate, bottomland"},
  {latin: "mūrus",
    english: "wall"},
  {latin: "taberna",
    english: "shop, tavern, inn"},
  {latin: "vīcus",
    english: "village"},
  {latin: "bonus",
    english: "good"},
  {latin: "laetus",
    english: "happy"},
  {latin: "magnus",
    english: "great, large"},
  {latin: "malus",
    english: "bad, evil"},
  {latin: "meus",
    english: "my, mine"},
  {latin: "miser",
    english: "sad, poor, wretched"},
  {latin: "multus",
    english: "much"},
  {latin: "multī",
    english: "many"},
  {latin: "noster",
    english: "our, ours"},
  {latin: "parvus",
    english: "small"},
  {latin: "paucī",
    english: "few, a few"},
  {latin: "tuus",
    english: "your, yours (s.)"},
  {latin: "vester",
    english: "your, yours (pl.)"},
  {latin: "Ītālus",
    english: "Italian"},
  {latin: "Lātīnus",
    english: "Latin, from Lazio"},
  {latin: "Rōmānus",
    english: "Roman"},
  {latin: "ā/ab",
    english: "from, away from"},
  {latin: "ad",
    english: "to, toward, for the purpose of"},
  {latin: "dō, dare",
    english: "to give"},
  {latin: "dēbeō, dēbēre",
    english: "to owe, ought, must"},
  {latin: "mōnstrō, mōnstrāre",
    english: "to show, to point out"},
  {latin: "narrō, narrāre",
    english: "to tell, to relate"},
  {latin: "nūntiō, nūntiāre",
    english: "to announce, to report"},
  {latin: "cēna",
    english: "supper, meal"},
  {latin: "cibus",
    english: "food"},
  {latin: "dōnum",
    english: "gift"},
  {latin: "fābula",
    english: "story, tale"},
  {latin: "histōria",
    english: "story, history"},
  {latin: "verbum",
    english: "word"},
  {latin: "aedificium",
    english: "building"},
  {latin: "ātrium",
    english: "atrium, main hall"},
  {latin: "caelum",
    english: "sky, heaven"},
  {latin: "cubiculum",
    english: "bedroom"},
  {latin: "fōrum",
    english: "outdoor marketplace, plaza"},
  {latin: "frūmentum",
    english: "grain"},
  {latin: "ientāculum",
    english: "breakfast"},
  {latin: "oppidum",
    english: "town"},
  {latin: "ovum",
    english: "egg"},
  {latin: "prandium",
    english: "lunch"},
  {latin: "templum",
    english: "temple"},
  {latin: "trīclinium",
    english: "dining room"},
  {latin: "vīnum",
    english: "wine"},
  {latin: "Lātium",
    english: "Latium, Lazio"},
  {latin: "cuius?",
    english: "whose?"},
  {latin: "cui?",
    english: "to whom? for whom?"},
  {latin: "quōcum?",
    english: "with whom?"},
  {latin: "quō?",
    english: "whom? (Ablative case)"}
]

function shuffle(array) {
  let k = []
  for (let i = array.length - 1; i >= 0; i--) {
    let j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
    k.push(array[i]);
  }
  return k;
}

function displayRandom(array) {
  let j = 1
  let iteration = ""
  let shuffledArray = shuffle(array);
  let html = `<div class="carousel-item active"><h6 class="latin-span">${shuffledArray[0].latin}</h6>
    <span id="translation${j}" class="vocab-span">${shuffledArray[0].english}</span></div>`
  for (let i = 1; i < array.length - 1; i++) {
    j++;
    iteration = `<div class="carousel-item">`;
    iteration += `<h6 class="latin-span">${shuffledArray[i].latin}</h6>`;
    iteration += `<p id="translation${j}" class="vocab-span" style="display: none">${shuffledArray[i].english}</p>`;
    iteration += `</div>`;
    html += iteration;
  }
  return html;
}

function displayRandomEngLat(array) {
  let j = 1
  let iteration = ""
  let shuffledArray = shuffle(array);
  let html = `<div class="carousel-item active"><h6 class="latin-span">${shuffledArray[0].english}</h6>
    <span id="translation${j}" class="vocab-span" style="display: none">${shuffledArray[0].latin}</span></div>`
  for (let i = 1; i < array.length - 1; i++) {
    j++;
    iteration = `<div class="carousel-item">`;
    iteration += `<h6 class="latin-span">${shuffledArray[i].english}</h6>`;
    iteration += `<p id="translation${j}" class="vocab-span">${shuffledArray[i].latin}</p>`;
    iteration += `</div>`;
    html += iteration;
  }
  return html;
}

console.log(displayRandomEngLat(allVolumeIVocab));
