const vocabDN = [
  {latin: "antīquitās",
    english: "antiquity, ancient times"},
  {latin: "benīgnitās",
    english: "kindness"},
  {latin: "bonitās",
    english: "goodness"},
  {latin: "brevitās",
    english: "brevity, shortness"},
  {latin: "captīvitās",
    english: "captivity"},
  {latin: "cāritās",
    english: "dearness, preciousness, charity"},
  {latin: "celeritās",
    english: "swiftness, speed"},
  {latin: "clāritās",
    english: "clarity, brightness"},
  {latin: "difficultās",
    english: "difficulty, lack of ability, hardship"},
  {latin: "dulcitās",
    english: "sweetness"},
  {latin: "facilitās",
    english: "ease"},
  {latin: "facultās",
    english: "ability, skill"},
  {latin: "falsitās",
    english: "falsehood"},
  {latin: "fēlīcitās",
    english: "happiness, good luck"},
  {latin: "grāvitās",
    english: "heaviness, weight, seriousness"},
  {latin: "humānitās",
    english: "humanity"},
  {latin: "humilitās",
    english: "humility, lowness"},
  {latin: "īnfēlīcitās",
    english: "unhappiness, bad luck"},
  {latin: "integritās",
    english: "wholeness, integrity"},
  {latin: "levitās",
    english: "lightness, unseriousness"},
  {latin: "lībertās",
    english: "freedom, liberty"},
  {latin: "longinquitās",
    english: "distance"},
  {latin: "novitās",
    english: "newness"},
  {latin: "obscūritās",
    english: "darkness"},
  {latin: "parvitās",
    english: "smallness"},
  {latin: "paupertās",
    english: "poverty"},
  {latin: "profunditās",
    english: "depth, profundity"},
  {latin: "propinquitās",
    english: "nearness"},
  {latin: "pūritās",
    english: "purity, cleanliness"},
  {latin: "sānctitās",
    english: "sanctity, holiness, saintliness"},
  {latin: "trīnitās",
    english: "triad"},
  {latin: "ūnitās",
    english: "unity, oneness"},
  {latin: "validitās",
    english: "strength, validity"},
  {latin: "vēlōcitās",
    english: "speed, quickness"},
  {latin: "vēritās",
    english: "truth"},
  {latin: "vetustās",
    english: "old age, long existence"},
  {latin: "ācritūdō",
    english: "sharpness, fierceness, bitterness"},
  {latin: "altitūdō",
    english: "height"},
  {latin: "dissimilitūdō",
    english: "dissimilarity, lack of resemblance"},
  {latin: "fortitūdō",
    english: "bravery, courage, strength"},
  {latin: "lātitūdō",
    english: "width"},
  {latin: "longitūdō",
    english: "length"},
  {latin: "magnitūdō",
    english: "size, greatness"},
  {latin: "pulchritūdō",
    english: "beauty"},
  {latin: "similitūdō",
    english: "similarity, resemblance"},
  {latin: "turpitūdō",
    english: "ugliness, shamefulness"},
  {latin: "iuventūs",
    english: "youth"},
  {latin: "senectūs",
    english: "old age"},
  {latin: "servitūs",
    english: "slavery, servitude"},
  {latin: "virtūs",
    english: "manhood, courage, virtue"},
  {latin: "amīcitia",
    english: "friendliness, friendship"},
  {latin: "angustia",
    english: "narrowness"},
  {latin: "audācia",
    english: "boldness, audacity"},
  {latin: "inimīcitia",
    english: "unfriendliness"},
  {latin: "laetitia",
    english: "happiness"},
  {latin: "malitia",
    english: "evil, malice"},
  {latin: "miseria",
    english: "sadness, misery, woe"},
  {latin: "potentia",
    english: "strength, power"},
  {latin: "sapientia",
    english: "wisdom"},
  {latin: "trīstitia",
    english: "sadness, melancholy"},
  {latin: "albēdō",
    english: "whiteness"},
  {latin: "dulcēdō",
    english: "sweetness"},
  {latin: "flāvēdō",
    english: "yellowness"},
  {latin: "nigrēdō",
    english: "blackness"},
  {latin: "rubēdō",
    english: "redness"},
  {latin: "calor",
    english: "heat"},
  {latin: "candor",
    english: "brilliant whiteness, frankness"},
  {latin: "frīgor",
    english: "coldness"},
  {latin: "tepor",
    english: "warmth"}
]

const vocab3PP = [
  {latin: "dedī",
    english: "I have given"},
  {latin: "iūvī",
    english: "I have helped"},
  {latin: "lāvī",
    english: "I have washed"},
  {latin: "stetī",
    english: "I have stood"},
  {latin: "vetuī",
    english: "I have forbidden"},
  {latin: "habuī",
    english: "I have had"},
  {latin: "docuī",
    english: "I have taught"},
  {latin: "ausus sum",
    english: "I have dared"},
  {latin: "auxī",
    english: "I have increased"},
  {latin: "fāvī",
    english: "I have favored"},
  {latin: "gavīsus sum",
    english: "I have rejoiced"},
  {latin: "iūssī",
    english: "I have ordered"},
  {latin: "lūxī",
    english: "I have shone"},
  {latin: "mānsī",
    english: "I have stayed"},
  {latin: "mōvī",
    english: "I have moved"},
  {latin: "plēvī",
    english: "I have filled"},
  {latin: "respondī",
    english: "I have replied"},
  {latin: "rīsī",
    english: "I have laughed/smiled"},
  {latin: "suāsī",
    english: "I have persuaded"},
  {latin: "vīdī",
    english: "I have seen"},
  {latin: "fuī",
    english: "I have been"},
  {latin: "potuī",
    english: "I have been able"},
  {latin: "āfuī",
    english: "I have been absent"},
  {latin: "adfuī",
    english: "I have been present"},
  {latin: "praefuī",
    english: "I have been in charge"},
  {latin: "īvī/iī",
    english: "I have gone"},
  {latin: "voluī",
    english: "I have wanted"},
  {latin: "nōluī",
    english: "I have not wanted/refused"},
  {latin: "factus sum",
    english: "I have become"},
  {latin: "adōrāvī",
    english: "I have worshipped"},
  {latin: "amāvī",
    english: "I have loved/liked"},
  {latin: "ambulāvī",
    english: "I have walked"},
  {latin: "clāmāvī",
    english: "I have shouted"},
  {latin: "dēbuī",
    english: "I have owed"},
  {latin: "docuī",
    english: "I have taught"},
  {latin: "equitāvī",
    english: "I have ridden"},
  {latin: "errāvī",
    english: "I have wandered"},
  {latin: "habuī",
    english: "I have had"},
  {latin: "habitāvī",
    english: "I have dwelt"},
  {latin: "iacuī",
    english: "I have lain"},
  {latin: "lābōrāvī",
    english: "I have worked/suffered"},
  {latin: "līberāvī",
    english: "I have freed"},
  {latin: "monuī",
    english: "I have warned"},
  {latin: "narrāvī",
    english: "I have told/related"},
  {latin: "natāvī",
    english: "I have swum"},
  {latin: "nāvigāvī",
    english: "I have sailed"},
  {latin: "nūntiāvī",
    english: "I have announced/reported"},
  {latin: "occupāvī",
    english: "I have seized"},
  {latin: "ōrāvī",
    english: "I have prayed"},
  {latin: "parāvī",
    english: "I have prepared"},
  {latin: "portāvī",
    english: "I have carried"},
  {latin: "prōhibuī",
    english: "I have prevented/stopped"},
  {latin: "pugnāvī",
    english: "I have fought"},
  {latin: "saltāvī",
    english: "I have leapt/danced"},
  {latin: "salūtāvī",
    english: "I have greeted"},
  {latin: "servāvī",
    english: "I have guarded/kept/saved"},
  {latin: "spectāvī",
    english: "I have watched/looked at"},
  {latin: "tenuī",
    english: "I have held"},
  {latin: "timuī",
    english: "I have feared"},
  {latin: "terruī",
    english: "I have frighted"},
  {latin: "vocāvī",
    english: "I have called/summoned"},
  {latin: "volāvī",
    english: "I have flown"},
  {latin: "appellāvī",
    english: "I have named/called"},
  {latin: "appropinquāvī",
    english: "I have approached"},
  {latin: "cēlāvī",
    english: "I have hidden"},
  {latin: "cēnāvī",
    english: "I have dined"},
  {latin: "cōgitāvī",
    english: "I have thought"},
  {latin: "cūrāvī",
    english: "I have cared/cared for"},
  {latin: "decuit",
    english: "it was proper"},
  {latin: "doluī",
    english: "I have hurt/grieved"},
  {latin: "formāvī",
    english: "I have formed/shaped"},
  {latin: "horruī",
    english: "I have trembled"},
  {latin: "imperāvī",
    english: "I have commanded"},
  {latin: "interfuī",
    english: "I have made a difference"},
  {latin: "iūrāvī",
    english: "I have sworn"},
  {latin: "licuit",
    english: "it was permitted"},
  {latin: "locāvī",
    english: "I have placed"},
  {latin: "nēcāvī",
    english: "I have killed"},
  {latin: "negāvī",
    english: "I have denied"},
  {latin: "nocuī",
    english: "I have harmed"},
  {latin: "nōmināvī",
    english: "I have named/appointed"},
  {latin: "novāvī",
    english: "I have renewed"},
  {latin: "numerāvī",
    english: "I have counted"},
  {latin: "oportuit",
    english: "it was necessary"},
  {latin: "oppugnāvī",
    english: "I have attacked"},
  {latin: "paruī",
    english: "I have obeyed"},
  {latin: "placuī",
    english: "I have pleased"},
  {latin: "potāvī",
    english: "I have drunk"},
  {latin: "properāvī",
    english: "I have hurried"},
  {latin: "putāvī",
    english: "I have thought/considered"},
  {latin: "rogāvī",
    english: "I have asked"},
  {latin: "soluī",
    english: "I have been accustomed"},
  {latin: "spērāvī",
    english: "I have hoped"},
  {latin: "spīrāvī",
    english: "I have breathed"},
  {latin: "studuī",
    english: "I have studied/been enthused about"},
  {latin: "superāvī",
    english: "I have overcome/defeated"},
  {latin: "tacuī",
    english: "I have been silent"},
  {latin: "temptāvī",
    english: "I have tried"},
  {latin: "valuī",
    english: "I have been strong/fared well"},
  {latin: "vulnerāvī",
    english: "I have wounded"},
  {latin: "dōnāvī",
    english: "I have granted"},
  {latin: "clārāvī",
    english: "I have made clear"},
  {latin: "dēclārāvī",
    english: "I have declared"},
  {latin: "obscūrāvī",
    english: "I have darkened/concealed"},
  {latin: "offuscāvī",
    english: "I have darkened/become dark"},
  {latin: "ōrdināvī",
    english: "I have put in order/ordained"},
  {latin: "gregāvī",
    english: "I have herded/assembled"},
  {latin: "lucuī",
    english: "I have shone"},
]

const vocab38 = [
  {latin: "aestās",
    english: "summer",
    notes: "Genitive = <strong>aestātis</strong>"},
  {latin: "aetās",
    english: "age, lifespan, generation",
    notes: "Genitive = <strong>aetātis</strong>"},
  {latin: "annus",
    english: "year",
    notes: "Genitive = <strong>annī</strong>"},
  {latin: "diēs",
    english: "day",
    notes: "Genitive = <strong>diēī</strong> (Decl. V)"},
  {latin: "hiems",
    english: "winter",
    notes: "Genitive = <strong>hiemis</strong>"},
  {latin: "hōra",
    english: "hour",
    notes: "Genitive = <strong>hōrae</strong>"},
  {latin: "hōrologium",
    english: "clock",
    notes: "Genitive = <strong>hōrologiī</strong>"},
  {latin: "īdūs",
    english: "Ides",
    notes: "Genitive = <strong>īduum</strong> (Decl. IV plural)"},
  {latin: "kalendae",
    english: "Kalends",
    notes: "Genitive = <strong>kalendārum</strong> (plural only)"},
  {latin: "kalendārium",
    english: "calendar",
    notes: "Genitive = <strong>kalendāriī</strong>"},
  {latin: "mēnsis",
    english: "month",
    notes: "Genitive = <strong>mēnsis (-ium)</strong>"},
  {latin: "merīdiēs",
    english: "noon, south",
    notes: "Genitive = <strong>merīdiēī</strong> (Decl. V)"},
  {latin: "nōnae",
    english: "Nones",
    notes: "Genitive = <strong>nōnārum</strong> (plural only)"},
  {latin: "vēr",
    english: "spring",
    notes: "Genitive = <strong>vēris</strong>"},
  {latin: "aestīvus",
    english: "estival, summery, summer-related"},
  {latin: "aeternus",
    english: "eternal"},
  {latin: "annuālis",
    english: "yearly"},
  {latin: "diārius",
    english: "daily"},
  {latin: "hibernus",
    english: "wintry, winter-related"},
  {latin: "mēnstruus",
    english: "monthly"},
  {latin: "vērnālis",
    english: "vernal, spring-related"},
  {latin: "autumnālis",
    english: "autumnal, fall-related"},
  {latin: "prīmus",
    english: "first"},
  {latin: "secundus",
    english: "second"},
  {latin: "tertius",
    english: "third"},
  {latin: "quārtus",
    english: "fourth"},
  {latin: "quīntus",
    english: "fifth"},
  {latin: "sextus",
    english: "sixth"},
  {latin: "septimus",
    english: "seventh"},
  {latin: "octāvus",
    english: "eighth"},
  {latin: "nōnus",
    english: "ninth"},
  {latin: "decimus",
    english: "tenth"},
  {latin: "ūndecimus",
    english: "eleventh"},
  {latin: "duodecimus",
    english: "twelfth"},
  {latin: "Iānuārius",
    english: "January"},
  {latin: "Februārius",
    english: "February"},
  {latin: "Mārtius",
    english: "March, belonging to the god Mars"},
  {latin: "Aprīlis",
    english: "April"},
  {latin: "Māius",
    english: "May"},
  {latin: "Iūnius",
    english: "June"},
  {latin: "Iūlius",
    english: "July"},
  {latin: "Augustus",
    english: "August, august, majestic"},
  {latin: "September",
    english: "September"},
  {latin: "Octōber",
    english: "October"},
  {latin: "November",
    english: "November"},
  {latin: "December",
    english: "December"},
  {latin: "cotīdiē",
    english: "every day, daily"},
  {latin: "crās",
    english: "tomorrow"},
  {latin: "diū",
    english: "for a long time",
    notes: "superlative = <strong>diūtissimē</strong>"},
  {latin: "herī",
    english: "yesterday"},
  {latin: "hōdiē",
    english: "today"},
  {latin: "iam",
    english: "already, as of now"},
  {latin: "nōn iam",
    english: "no longer"},
  {latin: "mox",
    english: "soon"},
  {latin: "numquam",
    english: "never"},
  {latin: "nōn numquam",
    english: "sometimes",
    notes: "also spelled <strong>nōnnumquam</strong>"},
  {latin: "ōlim",
    english: "once upon a time, formerly"},
  {latin: "postrīdiē",
    english: "on the day after, the next day"},
  {latin: "prīdiē",
    english: "on the day before, the previous day"},
  {latin: "quamdiū?",
    english: "how long?"},
  {latin: "saepe",
    english: "often",
    notes: "superlative = <strong>saepissimē</strong>"},
  {latin: "statim",
    english: "immediately"},
  {latin: "subitō",
    english: "suddenly"},
  {latin: "umquam",
    english: "ever, at any time"},
]

const vocab42 = [
  {latin: "audīvī",
    english: "I have heard/listened to",
    notes: "audiō, audīre"},
  {latin: "custōdīvī",
    english: "I have guarded/protected",
    notes: "custōdiō, custōdīre"},
  {latin: "dormīvī",
    english: "I have slept",
    notes: "dormiō, dormīre"},
  {latin: "ēsurīvī",
    english: "I have been hungry",
    notes: "ēsuriō, ēsurīre"},
  {latin: "fīnīvī",
    english: "I have finished/bounded",
    notes: "fīniō, fīnīre"},
  {latin: "ignīvī",
    english: "I have lit/set fire to",
    notes: "igniō, ifnīre"},
  {latin: "mūnīvī",
    english: "I have fortified/strengthened",
    notes: "mūniō, mūnīre"},
  {latin: "nescīvī",
    english: "I have not known",
    notes: "nesciō, nescīre"},
  {latin: "pūnīvī",
    english: "I have punished",
    notes: "pūniō, pūnīre"},
  {latin: "scīvī",
    english: "I have known",
    notes: "sciō, scīre"},
  {latin: "servīvī",
    english: "I have served",
    notes: "serviō, servīre (with a Dative object)"},
  {latin: "aperuī",
    english: "I have opened/revealed",
    notes: "aperiō, aperīre"},
  {latin: "sēnsī",
    english: "I have felt",
    notes: "sentiō, sentīre"},
  {latin: "vēnī",
    english: "I have come",
    notes: "veniō, venīre"},
  {latin: "ēgī",
    english: "I have done/driven",
    notes: "agō, agere"},
  {latin: "bibī",
    english: "I have drunk",
    notes: "bibō, bibere"},
  {latin: "cucurrī",
    english: "I have run",
    notes: "currō, currere"},
  {latin: "dīxī",
    english: "I have said/told",
    notes: "dīcō, dīcere"},
  {latin: "ēdī",
    english: "I have eaten",
    notes: "edō, edere"},
  {latin: "frēgī",
    english: "I have broken",
    notes: "frangō, frangere"},
  {latin: "gessī",
    english: "I have borne/worn/carried on",
    notes: "gerō, gerere"},
  {latin: "iūnxī",
    english: "I have joined",
    notes: "iūngō, iūngere"},
  {latin: "lūsī",
    english: "I have played",
    notes: "lūdō, lūdere"},
  {latin: "mīsī",
    english: "I have sent",
    notes: "mittō, mittere"},
  {latin: "nōvī",
    english: "I have known/been acquainted with",
    notes: "nōscō, nōscere"},
  {latin: "ostendī",
    english: "I have shown off",
    notes: "ostendō, ostendere"},
  {latin: "posuī",
    english: "I have put/placed",
    notes: "pōnō, pōnere"},
  {latin: "quaesīvī",
    english: "I have sought out/inquired",
    notes: "quaerō, quaerere"},
  {latin: "rēxī",
    english: "I have ruled",
    notes: "rēgō, rēgere"},
  {latin: "strūxī",
    english: "I have built",
    notes: "struō, struere"},
  {latin: "tetigī",
    english: "I have touched",
    notes: "tangō, tangere"},
  {latin: "vīcī",
    english: "I have conquered/won",
    notes: "vincō, vincere"},
  {latin: "clausī",
    english: "I have closed",
    notes: "claudō, claudere"},
  {latin: "coēgī",
    english: "I have gathered/forced",
    notes: "cōgō, cōgere"},
  {latin: "dūxī",
    english: "I have led/taken along",
    notes: "dūcō, dūcere"},
  {latin: "fefellī",
    english: "I have deceived/misled",
    notes: "fallō, fallere"},
  {latin: "tulī",
    english: "I have borne, carried, endured",
    notes: "ferō, ferre"},
  {latin: "lēgī",
    english: "I have gathered/read",
    notes: "legō, legere"},
  {latin: "pepulī",
    english: "I have driven/pushed",
    notes: "pellō, pellere"},
  {latin: "petīvī",
    english: "I have sought/asked for",
    notes: "petō, petere"},
  {latin: "scrīpsī",
    english: "I have written",
    notes: "scrībō, scrībere"},
  {latin: "trāxī",
    english: "I have pulled/drawn/dragged",
    notes: "trahō, trahere"},
  {latin: "vertī",
    english: "I have turned",
    notes: "vertō, vertere"},
  {latin: "vīxī",
    english: "I have lived/been alive",
    notes: "vīvō, vīvere"},
  {latin: "ninxit",
    english: "it has snowed",
    notes: "ningit, ningere"},
  {latin: "plūvit/pluit",
    english: "it has rained",
    notes: "pluit, pluere"},
  {latin: "cēpī",
    english: "I have taken",
    notes: "capiō, capere"},
  {latin: "cupīvī",
    english: "I have desired/wanted",
    notes: "cupiō, cupere"},
  {latin: "fēcī",
    english: "I have made/done",
    notes: "faciō, facere"},
  {latin: "fūgī",
    english: "I have fled",
    notes: "fugiō, fugere"},
  {latin: "iēcī",
    english: "I have thrown",
    notes: "iaciō, iacere"},
  {latin: "rapuī",
    english: "I have grabbed/carried off",
    notes: "rapiō, rapere"},
  {latin: "sapuī",
    english: "I have been wise/tasted",
    notes: "sapiō, sapere"},
  {latin: "cessī",
    english: "I have yielded/proceeded",
    notes: "cēdō, cēdere"},
  {latin: "crēvī",
    english: "I have grown",
    notes: "crēscō, crēscere"},
  {latin: "didicī",
    english: "I have learned",
    notes: "discō, discere"},
  {latin: "statuī",
    english: "I have set up/determined",
    notes: "statuō, statuere"},
  {latin: "trādidī",
    english: "I have handed over/surrendered",
    notes: "trādō, trādere"},
  {latin: "vexī",
    english: "I have transported/conveyed",
    notes: "vehō, vehere"},
  {latin: "volvī",
    english: "I have rolled/tumbled",
    notes: "volvō, volvere"}
]

const vocab42R = [
  {latin: "audītiō",
    english: "the act of hearing"},
  {latin: "apertūra",
    english: "opening, gap, hole"},
  {latin: "custōs",
    english: "caretaker, guardian",
    notes: "Genitive = <strong>custōdis</strong>"},
  {latin: "dormītōrium",
    english: "sleeping quarters"},
  {latin: "scientia",
    english: "knowledge, science"},
  {latin: "cōnscientia",
    english: "conscience, consciousness, awareness"},
  {latin: "servitium",
    english: "service"},
  {latin: "ignītiō",
    english: "the act of setting afire"},
  {latin: "mūnītiō",
    english: "the act of fortifying"},
  {latin: "cōnventiō",
    english: "the act of coming together"},
  {latin: "inventiō",
    english: "the act of discovering",
    notes: "with a Dative object"},
  {latin: "actiō",
    english: "the act of doing"},
  {latin: "dīctiō",
    english: "the act of saying/telling"},
  {latin: "frāctiō",
    english: "the act of breaking"},
  {latin: "iūnctiō",
    english: "the act of joining"},
  {latin: "missiō",
    english: "the act of sending"},
  {latin: "positiō",
    english: "the act of placing"},
  {latin: "strūctiō",
    english: "the act of building"},
  {latin: "in matrīmōnium dūcere",
    english: "to marry"},
  {latin: "petitiō",
    english: "the act of seeking/asking for"},
  {latin: "trāctiō",
    english: "the act of pulling"},
  {latin: "cōnsilium capere",
    english: "to make a plan, to take council"},
  {latin: "iter facere",
    english: "to travel/march"},
  {latin: "cōnsilium",
    english: "advice, council"},
  {latin: "sapor",
    english: "flavor",
    notes: "Genitive = <strong>sapōris</strong>"},
  {latin: "trāditiō",
    english: "the act of handing over/handing down"}
]

const vocab47 = [
  {latin: "interdum",
    english: "meanwhile"},
  {latin: "mane",
    english: "in the morning"},
  {latin: "nūper",
    english: "recently"},
  {latin: "praetereā",
    english: "besides, moreover"},
  {latin: "quondam",
    english: "once, formerly"},
  {latin: "sērō",
    english: "late",
    notes: "comparative = <strong>sērius</strong>; superlative = <strong>sērissimē</strong>"},
  {latin: "simul",
    english: "at the same time"},
  {latin: "dum",
    english: "while"},
  {latin: "clēmēns",
    english: "merciful",
    notes: "Genitive = <strong>clēmentis</strong>"},
  {latin: "clēmēntia",
    english: "mercy"},
  {latin: "communis",
    english: "common, shared"},
  {latin: "communitās",
    english: "community, commonwealth"},
  {latin: "crūdēlis",
    english: "cruel"},
  {latin: "crūdēlitās",
    english: "cruelty"},
  {latin: "dēmēns",
    english: "out of one's mind",
    notes: "Genitive = <strong>dēmentis</strong>"},
  {latin: "dementia",
    english: "insanity"},
  {latin: "dūrus",
    english: "hard, solid, lasting"},
  {latin: "dūritia",
    english: "hardness, rigor"},
  {latin: "hostīlis",
    english: "hostile",
    notes: "often with a Dative"},
  {latin: "hostīltās",
    english: "hostility, enmity"},
  {latin: "idōneus",
    english: "suitable, proper",
    notes: "often with a Dative"},
  {latin: "ingēns",
    english: "huge, enormous",
    notes: "Genitive = <strong>ingentis</strong>"},
  {latin: "mendāx",
    english: "prone to lying",
    notes: "Genitive = <strong>mendācis</strong>"},
  {latin: "mendācium",
    english: "lie, falsehood, deception"},
  {latin: "mollis",
    english: "soft, pliant"},
  {latin: "mollitia",
    english: "softness"},
  {latin: "populāris",
    english: "popular, of the people"},
  {latin: "pūblicus",
    english: "public, belonging to the people"},
  {latin: "pūblicitās",
    english: "publicity, state of being public"},
  {latin: "salūber",
    english: "healthy, wholesome"},
  {latin: "salūs",
    english: "health, well-being"},
  {latin: "salūbritās",
    english: "healthiness, wholesomeness"},
  {latin: "sānus",
    english: "sound, healthy, well"},
  {latin: "sānitās",
    english: "soundness, wellness"},
  {latin: "agmen",
    english: "marching column",
    notes: "Genitive = <strong>agminis</strong>"},
  {latin: "crīmen",
    english: "verdict, judgment",
    notes: "Genitive = <strong>crīminis</strong>"},
  {latin: "crīminālis",
    english: "criminal, related to criminal law"},
  {latin: "grāmen",
    english: "grass, herbs",
    notes: "Genitive = <strong>grāminis</strong>"},
  {latin: "līmen",
    english: "threshold, lintel",
    notes: "Genitive = <strong>līminis</strong>"},
  {latin: "nūmen",
    english: "nod, divine will, spirit",
    notes: "Genitive = <strong>nūminis</strong>"},
  {latin: "ōmen",
    english: "portent, sign of things to come",
    notes: "Genitive = <strong>ōminis</strong>"},
  {latin: "decus",
    english: "honor, distinction",
    notes: "Genitive = <strong>decoris</strong>"},
  {latin: "lītus",
    english: "shore",
    notes: "Genitive = <strong>lītoris</strong>"},
  {latin: "onus",
    english: "burden, load, responsibility",
    notes: "Genitive = <strong>oneris</strong>"},
  {latin: "opus",
    english: "work, accomplishment",
    notes: "Genitive = <strong>operis</strong>"},
  {latin: "scelus",
    english: "evil deed, crime",
    notes: "Genitive = <strong>sceleris</strong>"},
  {latin: "scelestus",
    english: "wicked, criminal"},
  {latin: "iecur",
    english: "liver",
    notes: "Genitive = <strong>iecoris (iecinōris)</strong>"},
  {latin: "iūs",
    english: "right, law, judgment",
    notes: "Genitive = <strong>iūris</strong>"},
  {latin: "mel",
    english: "honey",
    notes: "Genitive = <strong>mellis</strong>"},
  {latin: "rūs",
    english: "the country, farmland",
    notes: "Genitive = <strong>rūris</strong>; Locative = <strong>rūrī</strong>"},
  {latin: "rūrālis",
    english: "rural, pertaining to the countryside"},
  {latin: "rūsticus",
    english: "country-style, rustic, back-woods"},
  {latin: "iūstus",
    english: "just, fair"},
  {latin: "iūstitia",
    english: "justice, fairness"},
  {latin: "lītorālis",
    english: "litoral, of the shore"},
  {latin: "decōrus",
    english: "proper, decorated"},
  {latin: "ōminōsus",
    english: "ominous, foreboding"},
  {latin: "līmināris",
    english: "liminal, pertaining to thresholds or boundaries"},
  {latin: "grāmineus",
    english: "grassy"},
  {latin: "anterus",
    english: "forward, in front",
    notes: "comparative = <strong>anterior</strong>; superlative = <strong>antīcus</strong>"},
  {latin: "citer",
    english: "near, on this side",
    notes: "comparative = <strong>citerior</strong>; superlative = <strong>citimus</strong>"},
  {latin: "exter",
    english: "outside, outer",
    notes: "comparative = <strong>exterior</strong>; superlative = <strong>extrēmus</strong>"},
  {latin: "īnferus",
    english: "low",
    notes: "comparative = <strong>inferior</strong>; superlative = <strong>īmus</strong>"},
  {latin: "medius",
    english: "in the middle, half"},
  {latin: "posterus",
    english: "behind, following",
    notes: "comparative = <strong>posterior</strong>; superlative = <strong>postrēmus</strong>"},
  {latin: "superus",
    english: "high, above",
    notes: "comparative = <strong>superior</strong>; superlative = <strong>suprēmus/summus</strong>"},
  {latin: "ulter",
    english: "far, beyond",
    notes: "comparative = <strong>ulterior</strong>; superlative = <strong>ultimus</strong>"},
  {latin: "cīs",
    english: "on this side (of)",
    notes: "+ Accusative"},
  {latin: "extrā",
    english: "outside",
    notes: "+ Accusative"},
  {latin: "infrā",
    english: "below",
    notes: "+ Accusative"},
  {latin: "intrā",
    english: "within, inside",
    notes: "+ Accusative"},
  {latin: "prae",
    english: "in front of",
    notes: "+ Accusative"},
  {latin: "suprā",
    english: "above",
    notes: "+ Accusative"},
  {latin: "ultrā",
    english: "beyond, father on",
    notes: "+ Accusative"},
  {latin: "Auster",
    english: "south wind"},
  {latin: "austrālis",
    english: "southern, southerly"},
  {latin: "Boreās",
    english: "north wind"},
  {latin: "boreālis",
    english: "northern, northerly"},
  {latin: "Eurus",
    english: "east wind"},
  {latin: "occidēns",
    english: "west, sunset",
    notes: "Genitive = <strong>occidentis</strong>"},
  {latin: "occidēntālis",
    english: "western, westerly"},
  {latin: "oriēns",
    english: "east, sunrise",
    notes: "Genitive = <strong>orientis</strong>"},
  {latin: "orientālis",
    english: "eastern, easterly"},
  {latin: "septentriō",
    english: "north",
    notes: "Genitive = <strong>septentriōnis</strong>"},
  {latin: "septentriōnālis",
    english: "northern, northerly"},
  {latin: "Zephyrus",
    english: "west wind"},
  {latin: "dexter",
    english: "(on the) right"},
  {latin: "sinister",
    english: "(on the) left"},
  {latin: "deorsum",
    english: "downward"},
  {latin: "prōrsus",
    english: "forward"},
  {latin: "rūrsum",
    english: "back, backward, again"},
  {latin: "sūrsum",
    english: "upward"},
  {latin: "subitō",
    english: "suddenly"},
  {latin: "umquam",
    english: "ever, at any time"}
]

const allVolumeIVVocab = vocab38.concat(vocab42,vocab42R,vocab47);

function shuffle(array) {
  let k = []
  for (let i = array.length - 1; i >= 0; i--) {
    let j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
    k.push(array[i]);
  }
  return k;
}

function displayRandom(array) {
  let j = 1
  let iteration = ""
  let shuffledArray = shuffle(array);
  let html = `<div class="carousel-item active"><h6 class="latin-span">${shuffledArray[0].latin}</h6>
    <span id="translation${j}" class="vocab-span">${shuffledArray[0].english}</span></div>`
  for (let i = 1; i < array.length - 1; i++) {
    j++;
    iteration = `<div class="carousel-item">`;
    iteration += `<h6 class="latin-span">${shuffledArray[i].latin}</h6>`;
    iteration += `<p id="translation${j}" class="vocab-span" style="display: none">${shuffledArray[i].english}</p>`;
    let vocabNotes = shuffledArray[i].notes;
    if (vocabNotes != null) {
      console.log(vocabNotes);
      iteration += `<p id="notes${j}" class="notes-span" style="display: none">${vocabNotes}</p>`;
    }
    iteration += `</div>`;
    html += iteration;
  }
  return html;
}

function displayRandomEngLat(array) {
  let j = 1
  let iteration = ""
  let shuffledArray = shuffle(array);
  let html = `<div class="carousel-item active"><h6 class="latin-span">${shuffledArray[0].english}</h6>
    <span id="translation${j}" class="vocab-span" style="display: none">${shuffledArray[0].latin}</span></div>`
  for (let i = 1; i < array.length - 1; i++) {
    j++;
    iteration = `<div class="carousel-item">`;
    iteration += `<h6 class="latin-span">${shuffledArray[i].english}</h6>`;
    iteration += `<p id="translation${j}" class="vocab-span">${shuffledArray[i].latin}</p>`;
    let vocabNotes = shuffledArray[i].notes;
    if (vocabNotes != null) {
      console.log(vocabNotes);
      iteration += `<p id="notes${j}" class="notes-span" style="display: none">${vocabNotes}</p>`;
    }
    iteration += `</div>`;
    html += iteration;
  }
  return html;
}

// console.log(allVolumeIVVocab);
