const vocab52 = [
  {latin: "acus",
    english: "needle",
    notes: "acūs"},
  {latin: "arcus",
    english: "bow, arch, rainbow",
    notes: "arcūs"},
  {latin: "fētus",
    english: "offspring, bearing forth",
    notes: "fētūs"},
  {latin: "frūctus",
    english: "fruit, enjoyment, success",
    notes: "frūctūs"},
  {latin: "gradus",
    english: "step, degree, rank",
    notes: "gradūs"},
  {latin: "lacus",
    english: "lake, pond",
    notes: "lacūs"},
  {latin: "passus",
    english: "pace, two steps",
    notes: "passūs"},
  {latin: "mīlle passus",
    english: "a mile",
    notes: "pl. = mīlia passuum"},
  {latin: "sinus",
    english: "curve, lap, bay, gulf",
    notes: "sinūs"},
  {latin: "tribus",
    english: "tribe",
    notes: "tribūs"},
  {latin: "vultus",
    english: "countenance",
    notes: "vultūs"},
  {latin: "domus",
    english: "house, home, palace",
    notes: "domūs"},
  {latin: "manus",
    english: "hand, paw",
    notes: "manūs"},
  {latin: "pīnus",
    english: "pine tree, lance, spear",
    notes: "pīnūs"},
  {latin: "quercus",
    english: "oak",
    notes: "quercūs"},
  {latin: "acūtus",
    english: "sharp, pointy"},
  {latin: "domesticus",
    english: "domestic, of the home or homeland"},
  {latin: "domicilium",
    english: "dwelling, home, living quarters",
    notes: "domiciliī"},
  {latin: "fētōsus",
    english: "prolific, fertile"},
  {latin: "frūctifer",
    english: "fruit-bearing"},
  {latin: "gradātim",
    english: "step by step, gradually"},
  {latin: "manuālis",
    english: "manual, by hand"},
  {latin: "sinuōsus",
    english: "curvy"},
  {latin: "tribālis",
    english: "tribal, ethnic"},
  {latin: "tribūnus",
    english: "chief of a tribe, tribal councilmember",
    notes: "tribūnī"},
  {latin: "adventus",
    english: "arrival",
    notes: "adventūs"},
  {latin: "apparātus",
    english: "preparation, implement, tool",
    notes: "apparātūs"},
  {latin: "cēnsus",
    english: "count, estimation, appraisal",
    notes: "cēnsūs"},
  {latin: "cursus",
    english: "course, running",
    notes: "cursūs"},
  {latin: "coitus",
    english: "sexual intercourse",
    notes: "coitūs"},
  {latin: "exercitus",
    english: "army, trained military unit",
    notes: "exercitūs"},
  {latin: "magistrātus",
    english: "magistrate, magistracy",
    notes: "magistrātūs"},
  {latin: "nātus",
    english: "birth",
    notes: "nātūs"},
  {latin: "rīsus",
    english: "laughter, mockery, joking",
    notes: "rīsūs"},
  {latin: "sēnsus",
    english: "sense, feeling",
    notes: "sēnsūs"},
  {latin: "sexus",
    english: "anatomical sex",
    notes: "sexūs"},
  {latin: "spīritus",
    english: "breath, light breeze, spirit",
    notes: "spīritūs"},
  {latin: "status",
    english: "standing, sitaution, rank",
    notes: "statūs"},
  {latin: "ūsus",
    english: "use, experience",
    notes: "ūsūs"},
  {latin: "vīctus",
    english: "necessities of life, nourishment",
    notes: "vīctūs"},
  {latin: "cornū",
    english: "horn, tusk, wing of an army",
    notes: "cornūs"},
  {latin: "gelū",
    english: "frost, chill",
    notes: "gelūs"},
  {latin: "genū",
    english: "knee",
    notes: "genūs"},
  {latin: "advenīre",
    english: "to arrive, to approach, to come toward"},
  {latin: "apparāre",
    english: "to prepare, to equip, to provide"},
  {latin: "cēnsēre",
    english: "to count, to esimate, to give an opinion"},
  {latin: "coīre",
    english: "to meet, to go together"},
  {latin: "exercēre",
    english: "to train, to exercise"},
  {latin: "gelidus",
    english: "chilly, frosty, icy"},
  {latin: "nātālis",
    english: "relating to birth"},
  {latin: "secāre",
    english: "to cut, to divide"},
  {latin: "sectiō",
    english: "division, section, cutting",
    notes: "sectiōnis"},
  {latin: "sēnsuālis",
    english: "related to feelilng"},
  {latin: "spīrituālis",
    english: "related to spirit or breath"},
  {latin: "ūsuālis",
    english: "customary, developed from use or experience"},
  {latin: "aciēs",
    english: "sharp edge, battle line",
    notes: "aciēī"},
  {latin: "cariēs",
    english: "decay, rot, corruption",
    notes: "cariēī"},
  {latin: "ēsuriēs",
    english: "hunger",
    notes: "ēsuriēī"},
  {latin: "faciēs",
    english: "face, surface",
    notes: "faciēī"},
  {latin: "fīdēs",
    english: "faith, trust",
    notes: "fīdeī"},
  {latin: "prōgeniēs",
    english: "offspring, progeny",
    notes: "prōgeniēī"},
  {latin: "rabiēs",
    english: "madness, rage",
    notes: "rabiēī"},
  {latin: "requiēs",
    english: "rest",
    notes: "requiēī"},
  {latin: "rēs",
    english: "thing, matter, affair",
    notes: "reī"},
  {latin: "seriēs",
    english: "row, series, sequence",
    notes: "seriēī"},
  {latin: "speciēs",
    english: "appearance",
    notes: "speciēī"},
  {latin: "spēs",
    english: "hope",
    notes: "speī"},
  {latin: "in mediās rēs",
    english: "into the middle of things"},
  {latin: "in rē",
    english: "in the matter (of), in regard to"},
  {latin: "rēs frūmentāria",
    english: "grain supply"},
  {latin: "rēs gestae",
    english: "accompliments, deeds"},
  {latin: "rēs mīlitāris",
    english: "military science"},
  {latin: "rēs pūblica",
    english: "republic, commonmwealth"},
  {latin: "cariōsus",
    english: "rotten, decayed"},
  {latin: "faciālis",
    english: "facial, face-to-face"},
  {latin: "prōgenitor/-trīx",
    english: "ancestor",
    notes: "prōgenitōris/-trīcis"},
  {latin: "quiēs",
    english: "rest, quiet, calm",
    notes: "quiētis"},
  {latin: "rabidus",
    english: "mad, furious, raging"},
  {latin: "rabere",
    english: "rave, rage, be mad"},
  {latin: "speciālis",
    english: "specific, related to appearance"},
  {latin: "diēs nātālis",
    english: "birthday",
    notes: "diēī nātālis"},
  {latin: "centuria",
    english: "century, group of a hundred, military company",
    notes: "centuriae"},
  {latin: "eques",
    english: "horseman, knight",
    notes: "equitis"},
  {latin: "equitēs",
    english: "cavalry, gentry",
    notes: "equitum"},
  {latin: "equitātus",
    english: "cavalry unit",
    notes: "equitātūs"},
  {latin: "lēgātus",
    english: "lieutenant, envoy",
    notes: "lēgātī"},
  {latin: "manipulus",
    english: "maniple, handful, military brigade",
    notes: "manipulī"},
  {latin: "mīles",
    english: "soldier",
    notes: "mīlitis"},
  {latin: "pedes",
    english: "foot-soldier",
    notes: "peditis"},
  {latin: "peditēs",
    english: "infantry",
    notes: "peditum"},
  {latin: "ariēs",
    english: "ram, battering ram",
    notes: "aciētis"},
  {latin: "arma",
    english: "arms, weaponry",
    notes: "armōrum"},
  {latin: "ballista",
    english: "artillery device for hurling large rocks",
    notes: "ballistae"},
  {latin: "catapulta",
    english: "gigantic bow for firing large pikes",
    notes: "catapultae"},
  {latin: "hasta",
    english: "spear, lance, pike",
    notes: "hastae"},
  {latin: "pīlum",
    english: "throwing-spear, javelin",
    notes: "pīlī"},
  {latin: "tormentum",
    english: "siege engine, artillery device",
    notes: "tormentī"},
  {latin: "bellum",
    english: "war",
    notes: "bellī"},
  {latin: "castra",
    english: "camp, barracks",
    notes: "castrōrum"},
  {latin: "proelium",
    english: "battle",
    notes: "proeliī"},
  {latin: "testūdō",
    english: "tortoise, shielded battle formation",
    notes: "testūdinis"},
  {latin: "bellum gerere",
    english: "to wage war"},
  {latin: "proelium committere",
    english: "to begin battle"},
  {latin: "aciem instruere",
    english: "to form a battle line"},
  {latin: "castra pōnere",
    english: "to pitch camp"},
  {latin: "armāre",
    english: "to arm, to provide arms"},
  {latin: "bellāre",
    english: "to fight against"},
  {latin: "belligerere",
    english: "to wage war"},
  {latin: "bellātor/-trīx",
    english: "warrior",
    notes: "bellātrōris/-trīcis"},
  {latin: "manipulāris",
    english: "maniple-related"},
  {latin: "mīlitāris",
    english: "military, soldierly"},
  {latin: "proeliāris",
    english: "battle-related"},
  {latin: "testūdineus",
    english: "tortoise-like, tortoise-related"},
]

const vocab55 = [
  {latin: "cāsum est",
    english: "it has fallen, it has happened",
    notes: "cadō, cadere, cecidī, cāsum"},
  {latin: "caesum est",
    english: "it has been cut down",
    notes: "caedō, caedere, cecīdī, caesum"},
  {latin: "cēnsum est",
    english: "it has been counted/estimated/valued",
    notes: "cēnseō, cēnsēre, cēnsuī, cēnsum"},
  {latin: "fīsus sum",
    english: "I have trusted/had faith",
    notes: "fīdō, fīdere, fīsus sum"},
  {latin: "impedītum est",
    english: "it has been hindered/obstructed",
    notes: "impediō, -īre, -īvī, -ītum"},
  {latin: "levātum est",
    english: "it has been lifted/lightened/eased",
    notes: "levō, -āre, -āvī, -ātum"},
  {latin: "quiēvī",
    english: "I have rested",
    notes: "quiescō, quiescere, quiēvī, quiētum"},
  {latin: "sectum est",
    english: "it has been cut off/divided",
    notes: "secō, secāre, secuī, sectum"},
  {latin: "tortum est",
    english: "it has been twisted",
    notes: "torqueō, -ēre, torsī, tortum"},
  {latin: "vastātum est",
    english: "it has been destroyed/laid waste",
    notes: "vastō, -āre, -āvī, -ātum"},
  {latin: "vīnctum est",
    english: "it has been bound/fettered/fasten",
    notes: "vinciō, -īre, vīnxī, vīnctum"},
  {latin: "crēditum est",
    english: "it has been believed",
    notes: "crēdō, crēdere, crēdidī, crēditum"},
  {latin: "acceptum est",
    english: "it has been received/accepted",
    notes: "accipiō, -cipere, -cēpī, -ceptum"},
  {latin: "dēceptum est",
    english: "it has been deceived/entrapped",
    notes: "dēcipiō, -cipere, -cēpī, -ceptum"},
  {latin: "inceptum est",
    english: "it has been begun",
    notes: "incipiō, -cipere, -cēpī, -ceptum"},
  {latin: "susceptum est",
    english: "it has been undertaken/assumed",
    notes: "suscipiō, -cipere, -cēpī, -ceptum"},
  {latin: "cōnfectum est",
    english: "it has been accomplished/executed",
    notes: "cōnficiō, -ficere, -fēcī, -fectum"},
  {latin: "dēfectum est",
    english: "it has been exhausted/depleted/forsaken",
    notes: "dēficiō, -ficere, -fēcī, -fectum"},
  {latin: "interfectum est",
    english: "it has been killed/destroyed",
    notes: "interficiō, -ficere, -fēcī, -fectum"},
  {latin: "perfectum est",
    english: "it has been finished/completed",
    notes: "perficiō, -ficere, -fēcī, -fectum"},
  {latin: "coīvērunt",
    english: "they have assembled/united/copulated",
    notes: "coeō, -īre, -īvī, -ītum"},
  {latin: "perīvērunt",
    english: "they have perished/passed away",
    notes: "pereō, -īre, -īvī, -ītum"},
  {latin: "āmissum est",
    english: "it has been lost/let go",
    notes: "āmittō, -ere, -mīsī, -missum"},
  {latin: "commissum est",
    english: "it has been committed/begun/carried on",
    notes: "committō, -ere, -mīsī, -missum"},
  {latin: "prōmissum est",
    english: "it has been promised",
    notes: "prōmittō, -ere, -mīsī, -missum"},
  {latin: "adventum est",
    english: "it has been arrived at",
    notes: "adveniō, -venīre, -vēnī, -ventum"},
  {latin: "cognitum est",
    english: "it has been learned",
    notes: "cognōscō, -ere, cognōvī, cognitum"},
  {latin: "cōniectum est",
    english: "it has been hurled",
    notes: "cõniciō, cōnicere, cōniēcī, cōniectum"},
  {latin: "cōnscrīptum est",
    english: "it has been drafted/written up",
    notes: "cōnscrībō, -scrībere, -scrīpsī, -scrīptum"},
  {latin: "cōnsēnsum est",
    english: "it has been agreed up/permitted",
    notes: "cōnsentiō, -sentīre, -sēnsī, -sēnsum"},
  {latin: "cōnstitūtum est",
    english: "it has been decided/determined/set up",
    notes: "cōnstituō, -stituere, -stituī, -stitūtum"},
  {latin: "exercitum est",
    english: "it has been trained",
    notes: "exerceō, exercēre, exercuī, exercitum"},
  {latin: "instrūctum est",
    english: "it has been instructed/taught/built onto",
    notes: "instruō, -struere, -strūxī, -strūctum"},
  {latin: "intellēctum est",
    english: "it has been understood/noticed",
    notes: "intellegō, -legere, -lēxī, -lēctum"},
  {latin: "occidī",
    english: "I have fallen/died/been cut down",
    notes: "occidō, occidere, occidī, occāsum"},
  {latin: "occīsum est",
    english: "it has been cut down/slain",
    notes: "occīdō, occīdere, occīdī, occīsum"},
  {latin: "persuāsum est",
    english: "it has been persuaded",
    notes: "persuadeō, -ēre, -suāsī, -suāsum"},
  {latin: "prōscrīptum est",
    english: "it has been published/proclaimed/banned",
    notes: "prōscrībō, -scrībere, -scrīpsī, -scrīptum"},
  {latin: "cāsus",
    english: "case, occurrence"},
  {latin: "crēdibilis",
    english: "credible, believable"},
  {latin: "fīdus",
    english: "faithful, trustworthy, loyal"},
  {latin: "impedīmentum",
    english: "hindrance, impediment"},
  {latin: "impedīmenta",
    english: "baggage"},
  {latin: "tortiō",
    english: "torture, the act of twisting"},
  {latin: "tortuōsus",
    english: "twisty, winding"},
  {latin: "vinculum",
    english: "chain, fetter"},
  {latin: "is, ea, id",
    english: "he/she/it",
    notes: "eius, eī"},
  {latin: "eī, eae, ea",
    english: "they"},
  {latin: "īdem, eadem, idem",
    english: "the same",
    notes: "eiusdem, eīdem"},
]

const vocab59 = [
  {latin: "alius, alia, aliud",
    english: "another",
    notes: "alterīus, aliī"},
  {latin: "aliī..aliī",
    english: "some..others"},
  {latin: "alter, altera, alterum",
    english: "the other of two",
    notes: "alterīus, alterī"},
  {latin: "alter..alter",
    english: "one..the other"},
  {latin: "neuter, neutra, neutrum",
    english: "neither of two",
    notes: "neutrīus, neutrī"},
  {latin: "nūllus, -a, -um",
    english: "no, none",
    notes: "nūllīus, nūllī"},
  {latin: "sōlus, -a, -um",
    english: "only, alone",
    notes: "sōlīus, sōlī"},
  {latin: "tōtus, -a, -um",
    english: "the whole, all of",
    notes: "tōtīus, tōtī"},
  {latin: "ūllus, -a -um",
    english: "some, any",
    notes: "ūllīus, ūllī"},
  {latin: "uter, utra, utrum",
    english: "either of two",
    notes: "utrīus, utrī"},
  {latin: "uterque, utraque, utrumque",
    english: "each of two",
    notes: "utrīusque, utrīque"},
  {latin: "aliquis, aliquid",
    english: "someone, something",
    notes: "alicuius, alicui"},
  {latin: "quī, quae, quod",
    english: "who, which, that",
    notes: "cuius, cui"},
  {latin: "quisque, quidque",
    english: "each, everyone, everything",
    notes: "cuiusque, cuique"},
  {latin: "quisquis, quidquid",
    english: "anyone, anything",
    notes: "cuiuscuius, cuicui"},
  {latin: "hic, haec, hoc",
    english: "this, these, the latter",
    notes: "huius, huic"},
  {latin: "ille, illa, illud",
    english: "that, those, the former",
    notes: "illīus, illī"},
  {latin: "ipse, ipsa, ipsum",
    english: "-self (intensive pronoun)",
    notes: "ipsīus, ipsī"},
  {latin: "iste, ista, istud",
    english: "that, those, the former (with contempt)",
    notes: "istīus, istī"},
  {latin: "aedifex",
    english: "builder"},
  {latin: "artifex",
    english: "artist, artisan"},
  {latin: "auspex",
    english: "priest, augur, watcher of birds"},
  {latin: "augur",
    english: "priest, augur, watcher of birds"},
  {latin: "carnifex",
    english: "butcher, executioner"},
  {latin: "haruspex",
    english: "priest, inspector of entrails"},
  {latin: "index",
    english: "pointer, indicator, forefinger"},
  {latin: "iūdex",
    english: "judge, lawgiver"},
  {latin: "opifex",
    english: "craftsperson, laborer"},
  {latin: "pontifex",
    english: "high priest"},
  {latin: "potestās",
    english: "power, ability"},
  {latin: "tempestās",
    english: "weather, storm, season"},
  {latin: "voluntās",
    english: "free will, choice"},
  {latin: "voluptās",
    english: "pleasure, delight, pleasure-seeking"},
  {latin: "aedis",
    english: "temple, shrine, public building"},
  {latin: "aedificāre",
    english: "to build, to establish"},
  {latin: "aedīlis",
    english: "commissioner of public works"},
  {latin: "indicāre",
    english: "to point out, to indicate"},
  {latin: "iūdicāre",
    english: "to judge, to examine, to condemn"},
  {latin: "bōs",
    english: "ox, bovine"},
  {latin: "flōs",
    english: "flower, blossom"},
  {latin: "hospes",
    english: "guest, host"},
  {latin: "lapis",
    english: "stone"},
  {latin: "laus",
    english: "praise, honor"},
  {latin: "lepus",
    english: "hare, rabbit"},
  {latin: "mōs",
    english: "behavior, custom, tradition, habit"},
  {latin: "mūs",
    english: "mouse"},
  {latin: "pēs",
    english: "foot"},
  {latin: "sacerdōs",
    english: "priest, cleric"},
  {latin: "sanguis",
    english: "blood"},
  {latin: "bōvīnus",
    english: "oxlike, bovine"},
  {latin: "flōrālis",
    english: "flower-like, floral"},
  {latin: "lapidārius",
    english: "related to stones"},
  {latin: "leporīnus",
    english: "harelike"},
  {latin: "mōrālis",
    english: "customary, behavioral, moral"},
  {latin: "mūrīnus",
    english: "mouselike"},
  {latin: "pedālis",
    english: "foot-related"},
  {latin: "sacerdōtālis",
    english: "priestly, priest-related"},
  {latin: "sanguinārius",
    english: "blood-related"},
  {latin: "sanguineus",
    english: "bloody, blood-soaked"},
  {latin: "complūvium",
    english: "open roof of an atrium"},
  {latin: "dictum",
    english: "proverb, order, command"},
  {latin: "digitus",
    english: "finger"},
  {latin: "digitus pedis",
    english: "toe"},
  {latin: "dolor",
    english: "pain, grief, suffering"},
  {latin: "factum",
    english: "deed"},
  {latin: "fuga",
    english: "flight, escape"},
  {latin: "in fugam dare",
    english: "to put to flight"},
  {latin: "implūvium",
    english: "rain basin in an atrium"},
  {latin: "iūgum",
    english: "yoke, horse collar, mountain ridge"},
  {latin: "oculus",
    english: "eye"},
  {latin: "perīculum",
    english: "danger, risk"},
  {latin: "poena",
    english: "punishment, penalty"},
  {latin: "poenam dare",
    english: "to pay a penalty"},
  {latin: "pollex",
    english: "thumb"},
  {latin: "saxum",
    english: "rock"},
  {latin: "digitālis",
    english: "finger-related, digital"},
  {latin: "dolōrōsus",
    english: "painful, sorrowful"},
  {latin: "fugitīvus",
    english: "fleeing, in flight"},
  {latin: "oculāris",
    english: "eye-related, ocular"},
  {latin: "perīculōsus",
    english: "dangerous, perilous, risky"},
  {latin: "saxōsus",
    english: "rocky"}
]

const allVolumeVVocab = [
  {latin: "acus",
    english: "needle"},
  {latin: "arcus",
    english: "bow, arch, rainbow"},
  {latin: "fētus",
    english: "offspring, bearing forth"},
  {latin: "frūctus",
    english: "fruit, enjoyment, success"},
  {latin: "gradus",
    english: "step, degree, rank"},
  {latin: "lacus",
    english: "lake, pond"},
  {latin: "passus",
    english: "pace, two steps"},
  {latin: "mīlle passūs",
    english: "mile"},
  {latin: "sinus",
    english: "curve, lap, bay, gulf"},
  {latin: "tribus",
    english: "tribe"},
  {latin: "vultus",
    english: "countenance"},
  {latin: "domus",
    english: "house, home, palace"},
  {latin: "manus",
    english: "hand, paw"},
  {latin: "pīnus",
    english: "pine tree"},
  {latin: "quercus",
    english: "oak"},
  {latin: "acūtus",
    english: "sharp, pointy"},
  {latin: "domesticus",
    english: "domestic, of the home or homeland"},
  {latin: "domicilium",
    english: "dwelling, home, living quarters"},
  {latin: "fētōsus",
    english: "prolific, fertile"},
  {latin: "frūctifer",
    english: "fruit-bearing"},
  {latin: "gradātim",
    english: "step by step, gradually"},
  {latin: "manuālis",
    english: "manual, by hand"},
  {latin: "sinuōsus",
    english: "curvy"},
  {latin: "tribālis",
    english: "tribal, ethnic"},
  {latin: "tribūnus",
    english: "chief of a tribe, tribal councilmember"},
  {latin: "adventus",
    english: "arrival"},
  {latin: "apparātus",
    english: "preparation, implement, tool"},
  {latin: "cēnsus",
    english: "count, estimation, appraisal"},
  {latin: "cursus",
    english: "course, running"},
  {latin: "coitus",
    english: "sexual intercourse"},
  {latin: "exercitus",
    english: "army, trained military unit"},
  {latin: "magistrātus",
    english: "magistrate, magistracy"},
  {latin: "nātus",
    english: "birth"},
  {latin: "rīsus",
    english: "laughter, mockery, joking"},
  {latin: "sēnsus",
    english: "sense, feeling"},
  {latin: "sexus",
    english: "anatomical sex"},
  {latin: "spīritus",
    english: "breath, light breeze, spirit"},
  {latin: "status",
    english: "standing, sitaution, rank"},
  {latin: "ūsus",
    english: "use, experience"},
  {latin: "vīctus",
    english: "necessities of life, nourishment"},
  {latin: "cornū",
    english: "horn, tusk, wing of an army"},
  {latin: "gelū",
    english: "frost, chill"},
  {latin: "genū",
    english: "knee"},
  {latin: "advenīre",
    english: "to arrive, to approach, to come toward"},
  {latin: "apparāre",
    english: "to prepare, to equip, to provide"},
  {latin: "cēnsēre",
    english: "to count, to esimate, to give an opinion"},
  {latin: "coīre",
    english: "to meet, to go together"},
  {latin: "exercēre",
    english: "to train, to exercise"},
  {latin: "gelidus",
    english: "chilly, frosty, icy"},
  {latin: "nātālis",
    english: "relating to birth"},
  {latin: "diēs nātālis",
    english: "birthday"},
  {latin: "secāre",
    english: "to cut, to divide"},
  {latin: "sectiō",
    english: "division, section, cutting"},
  {latin: "sēnsuālis",
    english: "related to feelilng"},
  {latin: "spīrituālis",
    english: "related to spirit or breath"},
  {latin: "ūsuālis",
    english: "customary, developed from use or experience"},
  {latin: "aciēs",
    english: "sharp edge, battle line"},
  {latin: "cariēs",
    english: "decay, rot, corruption"},
  {latin: "ēsuriēs",
    english: "hunger"},
  {latin: "faciēs",
    english: "face, surface"},
  {latin: "fīdēs",
    english: "faith, trust"},
  {latin: "prōgeniēs",
    english: "offspring, progeny"},
  {latin: "rabiēs",
    english: "madness, rage"},
  {latin: "requiēs",
    english: "rest"},
  {latin: "rēs",
    english: "thing, matter, affair"},
  {latin: "seriēs",
    english: "row, series, sequence"},
  {latin: "speciēs",
    english: "appearance"},
  {latin: "spēs",
    english: "hope"},
  {latin: "in mediās rēs",
    english: "into the middle of things"},
  {latin: "in rē",
    english: "in the matter (of), in regard to"},
  {latin: "rēs frūmentāris",
    english: "grain supply"},
  {latin: "rēs gestae",
    english: "accompliments, deeds"},
  {latin: "rēs mīlitāris",
    english: "military science"},
  {latin: "rēs pūblica",
    english: "republic, commonmwealth"},
  {latin: "cariōsus",
    english: "rotten, decayed"},
  {latin: "faciālis",
    english: "facial, face-to-face"},
  {latin: "prōgenitor/-trīx",
    english: "ancestor"},
  {latin: "quiēs",
    english: "rest, quiet, calm"},
  {latin: "rabidus",
    english: "mad, furious, raging"},
  {latin: "rabere",
    english: "rave, rage, be mad"},
  {latin: "speciālis",
    english: "specific, related to appearance"},
  {latin: "centuria",
    english: "century, group of a hundred, military company"},
  {latin: "eques",
    english: "horseman, knight"},
  {latin: "equitēs",
    english: "cavalry, gentry"},
  {latin: "equitātus",
    english: "cavalry unit"},
  {latin: "lēgātus",
    english: "lieutenant, envoy"},
  {latin: "manipulus",
    english: "maniple, handful, military brigade"},
  {latin: "mīles",
    english: "soldier (in general)"},
  {latin: "pedes",
    english: "foot-soldier"},
  {latin: "peditēs",
    english: "infantry"},
  {latin: "ariēs",
    english: "ram, battering ram"},
  {latin: "arma",
    english: "arms, weaponry"},
  {latin: "ballista",
    english: "artillery device for hurling large rocks"},
  {latin: "catapulta",
    english: "gigantic bow for firing large pikes"},
  {latin: "hasta, pīnus",
    english: "spear, lance, pike"},
  {latin: "pīlum",
    english: "throwing-spear, javelin"},
  {latin: "tormentum",
    english: "siege engine, artillery device"},
  {latin: "bellum",
    english: "war"},
  {latin: "castra",
    english: "camp, barracks"},
  {latin: "proelium",
    english: "battle"},
  {latin: "testūdō",
    english: "tortoise, shielded battle formation"},
  {latin: "bellum gerere, belligerere",
    english: "to wage war"},
  {latin: "proelium committere",
    english: "to begin battle"},
  {latin: "aciem instruere",
    english: "to form a battle line"},
  {latin: "castra pōnere",
    english: "to pitch camp"},
  {latin: "armāre",
    english: "to arm, to provide arms"},
  {latin: "bellāre",
    english: "to fight against"},
  {latin: "bellātor/-trīx",
    english: "warrior"},
  {latin: "manipulāris",
    english: "maniple-related"},
  {latin: "mīlitāris",
    english: "military, soldierly"},
  {latin: "proeliāris",
    english: "battle-related"},
  {latin: "testūdineus",
    english: "tortoise-like, tortoise-related"},
  {latin: "cadere",
    english: "to fall, to happen"},
  {latin: "caedere",
    english: "to cut down"},
  {latin: "cēnsēre",
    english: "to count, to estimate, to value"},
  {latin: "fīdere",
    english: "to trust, to have faith"},
  {latin: "impedīre",
    english: "to hinder, to obstruct"},
  {latin: "levāre",
    english: "to lift, to lighten, to ease"},
  {latin: "quiescere",
    english: "to rest"},
  {latin: "secāre",
    english: "to cut off, to divide"},
  {latin: "torquēre",
    english: "to twist"},
  {latin: "vastāre",
    english: "to destroy, to lay waste"},
  {latin: "vincīre",
    english: "to bind, to fetter, to fasten"},
  {latin: "crēdere",
    english: "to believe"},
  {latin: "accipere",
    english: "to accept"},
  {latin: "dēcipere",
    english: "to deceive, to entrap"},
  {latin: "incipere",
    english: "to begin"},
  {latin: "suscipere",
    english: "to undertake, to assume"},
  {latin: "cōnficere",
    english: "to accomplish, to execute"},
  {latin: "dēficere",
    english: "to exhaust, to deplete, to forsake"},
  {latin: "interficere",
    english: "to kill"},
  {latin: "perficere",
    english: "to finish, to completed"},
  {latin: "coīre",
    english: "to assemble, to unite, to copulate"},
  {latin: "perīre",
    english: "to perish, to pass away"},
  {latin: "āmittere",
    english: "to lose, to let go"},
  {latin: "committere",
    english: "to commit, to begin, to carry on"},
  {latin: "prōmittere",
    english: "to promise"},
  {latin: "advenīre",
    english: "to arrive (at)"},
  {latin: "cognōscere",
    english: "to learn, to get to know"},
  {latin: "cōnicere",
    english: "to hurl"},
  {latin: "cōnscrībere",
    english: "to drafted, to write up"},
  {latin: "cōnsentīre",
    english: "to agree (to), to permit"},
  {latin: "cōnstituere",
    english: "to decide, to determine, to set up"},
  {latin: "exercēre",
    english: "to train, to exercise"},
  {latin: "instruere",
    english: "to instruct, to teach, to build onto"},
  {latin: "intellegere",
    english: "to understand, to notice"},
  {latin: "occidere",
    english: "to fall, to die, to be cut down"},
  {latin: "occīdere",
    english: "to cut down, to slay"},
  {latin: "persuādēre",
    english: "to persuade"},
  {latin: "prōscrībere",
    english: "to publish, to proclaim, to ban"},
  {latin: "cāsus",
    english: "case, occurrence"},
  {latin: "crēdibilis",
    english: "credible, believable"},
  {latin: "fīdus",
    english: "faithful, trustworthy, loyal"},
  {latin: "impedīmentum",
    english: "hindrance, impediment"},
  {latin: "impedīmenta",
    english: "baggage"},
  {latin: "tortiō",
    english: "torture, the act of twisting"},
  {latin: "tortuōsus",
    english: "twisty, winding"},
  {latin: "vinculum",
    english: "chain, fetter"},
  {latin: "is, ea, id",
    english: "he/she/it"},
  {latin: "eī, eae, ea",
    english: "they"},
  {latin: "īdem, eadem, idem",
    english: "the same"},
  {latin: "alius, alia, aliud",
    english: "another"},
  {latin: "aliī..aliī",
    english: "some..others"},
  {latin: "alter, altera, alterum",
    english: "the other of two"},
  {latin: "alter..alter",
    english: "one..the other"},
  {latin: "neuter, neutra, neutrum",
    english: "neither of two"},
  {latin: "nūllus, -a, -um",
    english: "no, none"},
  {latin: "sōlus, -a, -um",
    english: "only, alone"},
  {latin: "tōtus, -a, -um",
    english: "the whole, all of"},
  {latin: "ūllus, -a -um",
    english: "some, any"},
  {latin: "uter, utra, utrum",
    english: "either of two"},
  {latin: "uterque, utraque, utrumque",
    english: "each of two"},
  {latin: "aliquis, aliquid",
    english: "someone, something"},
  {latin: "quī, quae, quod",
    english: "who, which, that"},
  {latin: "quisque, quidque",
    english: "each, everyone, everything"},
  {latin: "quisquis, quidquid",
    english: "anyone, anything"},
  {latin: "hic, haec, hoc",
    english: "this, these, the latter"},
  {latin: "ille, illa, illud; iste, ista, istud",
    english: "that, those, the former"},
  {latin: "ipse, ipsa, ipsum",
    english: "-self (intensive pronoun)"},
  {latin: "aedifex",
    english: "builder"},
  {latin: "artifex",
    english: "artist, artisan"},
  {latin: "augur, auspex",
    english: "priest, augur, watcher of birds"},
  {latin: "carnifex",
    english: "butcher, executioner"},
  {latin: "haruspex",
    english: "priest, inspector of entrails"},
  {latin: "index",
    english: "pointer, indicator, forefinger"},
  {latin: "iūdex",
    english: "judge, lawgiver"},
  {latin: "opifex",
    english: "craftsperson, laborer"},
  {latin: "pontifex",
    english: "high priest"},
  {latin: "potestās",
    english: "power, ability"},
  {latin: "tempestās",
    english: "weather, storm, season"},
  {latin: "voluntās",
    english: "free will, choice"},
  {latin: "voluptās",
    english: "pleasure, delight, pleasure-seeking"},
  {latin: "aedis",
    english: "temple, shrine, public building"},
  {latin: "aedificāre",
    english: "to build, to establish"},
  {latin: "aedīlis",
    english: "commissioner of public works"},
  {latin: "indicāre",
    english: "to point out, to indicate"},
  {latin: "iūdicāre",
    english: "to judge, to examine, to condemn"},
  {latin: "bōs",
    english: "ox, bovine"},
  {latin: "flōs",
    english: "flower, blossom"},
  {latin: "hospes",
    english: "guest, host"},
  {latin: "lapis",
    english: "stone"},
  {latin: "laus",
    english: "praise, honor"},
  {latin: "lepus",
    english: "hare, rabbit"},
  {latin: "mōs",
    english: "behavior, custom, tradition, habit"},
  {latin: "mūs",
    english: "mouse"},
  {latin: "pēs",
    english: "foot"},
  {latin: "sacerdōs",
    english: "priest, cleric"},
  {latin: "sanguis",
    english: "blood"},
  {latin: "bōvīnus",
    english: "oxlike, bovine"},
  {latin: "flōrālis",
    english: "flower-like, floral"},
  {latin: "lapidārius",
    english: "related to stones"},
  {latin: "leporīnus",
    english: "harelike"},
  {latin: "mōrālis",
    english: "customary, behavioral, moral"},
  {latin: "mūrīnus",
    english: "mouselike"},
  {latin: "pedālis",
    english: "foot-related"},
  {latin: "sacerdōtālis",
    english: "priestly, priest-related"},
  {latin: "sanguinārius",
    english: "blood-related"},
  {latin: "sanguineus",
    english: "bloody, blood-soaked"},
  {latin: "complūvium",
    english: "open roof of an atrium"},
  {latin: "dictum",
    english: "proverb, order, command"},
  {latin: "digitus",
    english: "finger"},
  {latin: "digitus pedis",
    english: "toe"},
  {latin: "dolor",
    english: "pain, grief, suffering"},
  {latin: "factum",
    english: "deed"},
  {latin: "fuga",
    english: "flight, escape"},
  {latin: "in fugam dare",
    english: "to put to flight"},
  {latin: "implūvium",
    english: "rain basin in an atrium"},
  {latin: "iūgum",
    english: "yoke, horse collar, mountain ridge"},
  {latin: "oculus",
    english: "eye"},
  {latin: "perīculum",
    english: "danger, risk"},
  {latin: "poena",
    english: "punishment, penalty"},
  {latin: "poenam dare",
    english: "to pay a penalty"},
  {latin: "pollex",
    english: "thumb"},
  {latin: "saxum",
    english: "rock"},
  {latin: "digitālis",
    english: "finger-related, digital"},
  {latin: "dolōrōsus",
    english: "painful, sorrowful"},
  {latin: "fugitīvus",
    english: "fleeing, in flight"},
  {latin: "oculāris",
    english: "eye-related, ocular"},
  {latin: "perīculōsus",
    english: "dangerous, perilous, risky"},
  {latin: "saxōsus",
    english: "rocky"}
]

function shuffle(array) {
  let k = []
  for (let i = array.length - 1; i >= 0; i--) {
    let j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
    k.push(array[i]);
  }
  return k;
}

function displayRandom(array) {
  let j = 1
  let iteration = ""
  let shuffledArray = shuffle(array);
  let html = `<div class="carousel-item active"><h6 class="latin-span">${shuffledArray[0].latin}</h6>
    <span id="translation${j}" class="vocab-span">${shuffledArray[0].english}</span></div>`
  for (let i = 1; i < array.length - 1; i++) {
    j++;
    iteration = `<div class="carousel-item">`;
    iteration += `<h6 class="latin-span">${shuffledArray[i].latin}</h6>`;
    iteration += `<p id="translation${j}" class="vocab-span" style="display: none">${shuffledArray[i].english}</p>`;
    let vocabNotes = shuffledArray[i].notes;
    if (vocabNotes != null) {
      console.log(vocabNotes);
      iteration += `<p id="notes${j}" class="notes-span" style="display: none"><strong>${vocabNotes}</strong></p>`;
    }
    iteration += `</div>`;
    html += iteration;
  }
  return html;
}

function displayRandomEngLat(array) {
  let j = 1
  let iteration = ""
  let shuffledArray = shuffle(array);
  let html = `<div class="carousel-item active"><h6 class="latin-span">${shuffledArray[0].english}</h6>
    <span id="translation${j}" class="vocab-span" style="display: none">${shuffledArray[0].latin}</span></div>`
  for (let i = 1; i < array.length - 1; i++) {
    j++;
    iteration = `<div class="carousel-item">`;
    iteration += `<h6 class="latin-span">${shuffledArray[i].english}</h6>`;
    iteration += `<p id="translation${j}" class="vocab-span">${shuffledArray[i].latin}</p>`;
    let vocabNotes = shuffledArray[i].notes;
    if (vocabNotes != null) {
      console.log(vocabNotes);
      iteration += `<p id="notes${j}" class="notes-span" style="display: none">${vocabNotes}</p>`;
    }
    iteration += `</div>`;
    html += iteration;
  }
  return html;
}

console.log(allVolumeVVocab.length);
